using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;
using Franzo.Essentials.Roslyn;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Franzo.Essentials.InterfaceInheritance.Generator;

public partial class InterfaceInheritanceGenerator : IIncrementalGenerator
{
    internal static void Emit(Context context)
    {
        var sb = new StringBuilder();
        var writer = new IndentedTextWriter(new StringWriter(sb), "    ");

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine();
        writer.WriteLine("#nullable restore annotations");
        writer.WriteLine("#nullable disable warnings");
        writer.WriteLine("#nullable disable warnings");
        writer.WriteLine("#pragma warning disable CS0108");
        writer.WriteLine("#pragma warning disable CS0618");
        writer.WriteLine("#pragma warning disable CS8387");
        writer.WriteLine();

        foreach (var type in context.AnalysisData.RootTypesToEmit)
        {
            EmitTypeWithNamespaceDeclaration(type, writer, context);
        }

        context.SourceProductionContext.AddSource(
            "Franzo.Essentials.InterfaceInheritance.Generated.cs",
            sb.ToString());
    }

    internal static void EmitTypeWithNamespaceDeclaration(
        InternalTypeSymbol type,
        IndentedTextWriter writer,
        Context context)
    {
        if (!type.RoslynSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            writer.Write("namespace ");
            writer.Write(type.RoslynSymbol.ContainingNamespace.ToDisplayString());
            writer.WriteLine();
            writer.WriteBracedSectionStart();
        }

        EmitType(type, writer, context);

        if (!type.RoslynSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            writer.WriteBracedSectionEnd();
            writer.WriteLine();
        }
    }

    private static void EmitTypes(
        IEnumerable<InternalTypeSymbol> types,
        IndentedTextWriter writer,
        Context context)
    {
        foreach (var type in types)
        {
            EmitType(type, writer, context);
        }
    }

    private static void EmitType(
        InternalTypeSymbol type,
        IndentedTextWriter writer,
        Context context)
    {
        writer.Write("partial");

        if (type.RoslynSymbol.TypeKind is TypeKind.Interface)
        {
            writer.Write($" interface");
        }
        else
        {
            if (type.RoslynSymbol.IsRecord)
            {
                writer.Write(" record");
            }

            writer.Write(" ");
            writer.Write(type.RoslynSymbol.TypeKind is TypeKind.Class ? "class" : "struct");
        }

        writer.Write(" ");
        writer.Write(type.RoslynSymbol.Name);

        if (type.IsDataClass)
        {
            writer.Write(" : ");
            writer.Write(typeof(InterfaceData).GloballyQualifiedName());
            writer.Write("<");
            writer.Write(type.ContainingType!.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(">");
        }
        else if (type.RoslynSymbol.TypeKind.IsClassOrStruct())
        {
            if (type.AttributeSpecifiedDirectInterfaces.Count > 0)
            {
                writer.Write(" : ");
                foreach ((var i, var @interface) in type.AttributeSpecifiedDirectInterfaces.IndicesAndItems())
                {
                    writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
                    if (i != type.AttributeSpecifiedDirectInterfaces.Count - 1)
                    {
                        writer.Write(", ");
                    }
                }
            }
        }

        writer.WriteLine();
        writer.WriteBracedSectionStart();

        if (type.IsDataClass)
        {
            writer.Write("public static readonly global::System.Reflection.ConstructorInfo ");
            writer.Write(GeneratedConstructorPropertyName);
            writer.Write(" = typeof(");
            writer.Write(type.RoslynSymbol.ToDisplayString());
            writer.Write(").GetConstructors()[0];");
            writer.WriteLine();
        }

        if (type.RoslynSymbol.TypeKind.IsClassOrStruct())
        {
            if (!type.IsDataClass)
            {
                EmitRealDataFieldsAndDataPropertyImplementations(type, writer, context);
            }

            EmitFakeDataFieldsAndConstructors(type, writer, context);
        }

        if (type.DataClass is not null)
        {
            foreach (var property in type.DataClass.DeclaredProperties)
            {
                EmitDataClassPropertyProxy(
                    property.RoslynSymbol,
                    type.RoslynSymbol,
                    writer,
                    context);
            }

            foreach (var @event in type.DataClass.DeclaredEvents)
            {
                EmitDataClassEventProxy(
                    @event.RoslynSymbol,
                    type.RoslynSymbol,
                    writer,
                    context);
            }

            writer.Write("public ");
            writer.Write(type.DataClass.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(" ");
            writer.Write(GeneratedInterfaceDataPropertyName);
            writer.Write(" { get; }");
            writer.WriteLine();
        }

        foreach (var @interface in type.InterfacesInheriting)
        {
            foreach (var feature in @interface.DeclaredFeatures)
            {
                if (!(feature.RoslynSymbol.IsAccessibleFromType(
                        type.RoslynSymbol,
                        context.Compilation)
                     || feature.RoslynSymbol.DeclaredAccessibility is Accessibility.Protected
                     || (feature.RoslynSymbol.DeclaredAccessibility is Accessibility.ProtectedAndInternal
                          && feature.RoslynSymbol.ContainingAssembly.GivesAccessTo(
                            type.RoslynSymbol.ContainingAssembly)))
                    || feature.RoslynSymbol is IMethodSymbol
                    {
                        MethodKind: MethodKind.PropertyGet
                            or MethodKind.PropertySet
                            or MethodKind.EventAdd
                            or MethodKind.EventRemove
                    }
                    || feature.RoslynSymbol is IFieldSymbol
                    {
                        IsConst: false,
                        IsReadOnly: false
                    }
                    // @todo: once partial properties are in,
                    // we should change this so that we *do* emit inheritances for public abstract properties and methods,
                    // but just mark them them as partial
                    // (ideally we would do so for events too, but it doesn't look like partial events are coming any time soon)
                    || (feature.RoslynSymbol.DeclaredAccessibility is Accessibility.Public
                        && feature.RoslynSymbol.IsAbstract)
                    || feature.RoslynSymbol.Name == type.RoslynSymbol.Name)
                {
                    continue;
                }

                foreach (var shadowingType in feature.TypesDeclaringShadowingFeatures)
                {
                    if (type.RoslynSymbol.IsAssignableTo(
                            shadowingType.RoslynSymbol,
                            context.Compilation)
                        || type.AttributeSpecifiedDirectInterfaces.Any(
                            i => i.RoslynSymbol.IsAssignableTo(
                                shadowingType.RoslynSymbol,
                                context.Compilation)))
                    {
                        continue;
                    }
                }

                EmitFeatureInheritance(
                    feature,
                    @interface.RoslynSymbol,
                    type.RoslynSymbol,
                    writer,
                    context);
            }
        }

        foreach (var @interface in type.DirectInterfaces)
        {
            EmitAsInterfaceMethod(@interface, writer, context);
        }

        foreach (var memberType in type.DeclaredTypes)
        {
            EmitType(memberType, writer, context);
        }

        writer.WriteBracedSectionEnd();
    }

    private static void EmitRealDataFieldsAndDataPropertyImplementations(
        InternalTypeSymbol type,
        IndentedTextWriter writer,
        Context context)
    {
        var x = type.InterfacesInheriting.ToArray();
        foreach (var @interface in type.InterfacesInheriting)
        {
            if (@interface.DataClass is null) continue;

            writer.Write("private ");
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write(" ");
            EmitRealDataFieldName(@interface, writer);
            writer.WriteLine();

            writer.Indent++;
            writer.Write("= (");
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write(")global::System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(typeof(");
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write("));");
            writer.WriteLine();
            writer.Indent--;
        }

        foreach (var @interface in type.InterfacesInheriting)
        {
            if (@interface.DataClass is null) continue;

            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write(" ");
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(GeneratedInterfaceDataPropertyName);
            writer.WriteLine();

            writer.WriteBracedSectionStart();
            writer.Write("get => ");
            EmitRealDataFieldName(@interface, writer);
            writer.Write(";");
            writer.WriteLine();
            writer.WriteBracedSectionEnd();
        }
    }

    private static void EmitAsInterfaceMethod(
        InternalTypeSymbol @interface,
        IndentedTextWriter writer,
        Context context)
    {
        writer.Write("private ");
        writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
        writer.Write(" As");
        writer.Write(@interface.RoslynSymbol.Name.WithoutInterfaceI());
        writer.Write("()");
        writer.WriteLine();
        writer.WriteBracedSectionStart();
        writer.WriteLine("return this;");
        writer.WriteBracedSectionEnd();
    }

    private static void EmitFakeDataFieldsAndConstructors(
        InternalTypeSymbol type,
        IndentedTextWriter writer,
        Context context)
    {
        var anchorType = type;
        if (type.IsDataClass)
        {
            anchorType = type.ContainingType!;
        }

        foreach (var @interface in anchorType.DirectInterfaces)
        {
            if (@interface.DataClass is null) continue;

            writer.Write("private ");
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write(" ");
            EmitFakeDataFieldName(@interface, writer);
            writer.Write(";");
            writer.WriteLine();
        }

        foreach (var @interface in anchorType.DirectInterfaces)
        {
            if (@interface.DataClass is null) continue;

            writer.Write("private ");
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write(" Construct");
            writer.Write(@interface.RoslynSymbol.Name.WithoutInterfaceI());
            EmitMethodParameterList(
                @interface.DataClass.ConstructorIfDataClass!.RoslynSymbol,
                type.RoslynSymbol,
                writer,
                context);
            writer.WriteLine();
            writer.WriteBracedSectionStart();

            writer.Write("if (");
            if (type.IsDataClass)
            {
                writer.Write("((");
                writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
                writer.Write(")");
                writer.Write(nameof(InterfaceData<object>.This));
                writer.Write(").");
                writer.Write(GeneratedInterfaceDataPropertyName);
            }
            else
            {
                EmitRealDataFieldName(@interface, writer);
            }
            writer.Write(".");
            writer.Write(nameof(InterfaceData.__IsConstructed));
            writer.Write(") return null!;");
            writer.WriteLine();

            if (!type.IsDataClass)
            {
                foreach (var ancestorInterface in @interface.SelfAndInterfaces)
                {
                    if (ancestorInterface.DataClass is null) continue;

                    EmitRealDataFieldName(ancestorInterface, writer);
                    writer.Write(".");
                    writer.Write(nameof(InterfaceData<object>.__This));
                    writer.Write(" = this;");
                    writer.WriteLine();
                }
            }

            // @todo: remove string interpolations if needed for perf

            // @todo: create delegate and invoke that instead
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write(".");
            writer.Write(GeneratedConstructorPropertyName);
            writer.Write(".Invoke(");
            if (type.IsDataClass)
            {
                writer.Write("((");
                writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
                writer.Write(")");
                writer.Write(nameof(InterfaceData<object>.This));
                writer.Write(").");
                writer.Write(GeneratedInterfaceDataPropertyName);
            }
            else
            {
                EmitRealDataFieldName(@interface, writer);
            }
            writer.Write(", new object?[] { ");
            EmitUnparenthesizedArgumentListFromParameters(
                @interface.DataClass.ConstructorIfDataClass.RoslynSymbol.Parameters,
                writer);
            writer.Write(" });");
            writer.WriteLine();

            writer.WriteLine($"return null!;");

            writer.WriteBracedSectionEnd();
        }
    }

    private static void EmitFakeDataFieldName(
        InternalTypeSymbol @interface,
        IndentedTextWriter writer)
    {
        writer.Write(@interface.RoslynSymbol.Name.WithoutInterfaceI());
        writer.Write("Data");
    }

    private static void EmitRealDataFieldName(
        InternalTypeSymbol @interface,
        IndentedTextWriter writer)
    {
        writer.Write("__");
        EmitFakeDataFieldName(@interface, writer);
    }

    private static void EmitMainModifiers(
        ISymbol symbol,
        IndentedTextWriter writer,
        bool includeSealed = false)
    {
        EmitAccessibilityModifiers(symbol.DeclaredAccessibility, writer);

        if (includeSealed)
        {
            writer.Write(" sealed");
        }

        if (symbol.IsStatic && symbol is not IFieldSymbol { IsConst: true })
        {
            writer.Write(" static");
        }
    }

    private static void EmitAccessibilityModifiers(
        Accessibility accessibility,
        IndentedTextWriter writer)
    {
        if (accessibility is Accessibility.Public)
        {
            writer.Write("public");
        }
        else if (accessibility is Accessibility.Protected)
        {
            writer.Write("protected");
        }
        else if (accessibility is Accessibility.Internal)
        {
            writer.Write("internal");
        }
        else if (accessibility is Accessibility.Private)
        {
            writer.Write("private");
        }
        else if (accessibility is Accessibility.ProtectedOrInternal)
        {
            writer.Write("protected internal");
        }
        else if (accessibility is Accessibility.ProtectedAndInternal)
        {
            writer.Write("private protected");
        }
    }

    private static void EmitAttributes(
        ISymbol symbol,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context,
        bool separateLines)
    {
        var attributes = symbol.GetAttributes();
        // Note: protected/private protected member types in a interface CAN currently be accessed by implementing classes
        foreach ((var i, var attribute) in attributes.IndicesAndItems())
        {
            if (attribute.AttributeClass is null
                || attribute.AttributeClass.IsCompilerGeneratedAttributeType()
                || !attribute.AttributeClass.IsAccessibleFromType(withinType, context.Compilation)
                || attribute.AttributeClass.TypeArguments.Any(
                    a => !a.IsAccessibleFromType(withinType, context.Compilation))
                || attribute.ConstructorArguments
                    .Concat(attribute.NamedArguments.Select(p => p.Value))
                    .Any(arg => arg.Kind is TypedConstantKind.Error)
                || attribute.AttributeConstructor is null
                || !attribute.AttributeConstructor.IsAccessibleFromType(withinType, context.Compilation))
            {
                continue;
            }

            EmitAttribute(attribute, writer);

            if (separateLines)
            {
                writer.WriteLine();
            }
            else
            {
                if (i != attributes.Length - 1)
                {
                    writer.Write(" ");
                }
            }
        }
    }

    private static void EmitAttribute(AttributeData attribute, IndentedTextWriter writer)
    {
        writer.Write("[");
        writer.Write(attribute.AttributeClass!.ToFullyQualifiedDisplayString());
        writer.Write("(");

        foreach ((var i, var argument) in attribute.ConstructorArguments.IndicesAndItems())
        {
            EmitTypedConstant(argument, writer);
            if (i != attribute.ConstructorArguments.Length - 1
                || attribute.NamedArguments.Length > 0)
            {
                writer.Write(", ");
            }
        }

        foreach ((var i, var pair) in attribute.NamedArguments.IndicesAndItems())
        {
            writer.Write(pair.Key);
            writer.Write(" = ");
            EmitTypedConstant(pair.Value, writer);
            if (i != attribute.NamedArguments.Length - 1)
            {
                writer.Write(", ");
            }
        }

        writer.Write(")]");
    }

    private static void EmitTypedConstant(TypedConstant typedConstant, IndentedTextWriter writer)
    {
        Debug.Assert(typedConstant.Kind is not TypedConstantKind.Error && typedConstant.Type is not null);

        if (typedConstant.IsNull)
        {
            EmitNull(writer);
        }
        else
        {
            switch (typedConstant.Kind)
            {
                case TypedConstantKind.Array:
                    EmitArrayTypedConstant(typedConstant, writer);
                    break;
                case TypedConstantKind.Primitive or TypedConstantKind.Enum:
                    EmitConstant(typedConstant.Value, typedConstant.Type!, writer);
                    break;
                case TypedConstantKind.Type:
                    EmitTypeTypedConstant(typedConstant, writer);
                    break;
            };
        }
    }

    private static void EmitArrayTypedConstant(TypedConstant self, IndentedTextWriter writer)
    {
        Debug.Assert(self.Type is not null);

        var arrayType = (IArrayTypeSymbol)self.Type!;
        writer.Write("new ");
        writer.Write(arrayType.ElementType.ToFullyQualifiedDisplayString());
        writer.Write("[] { ");
        EmitCommaSeparatedTypedConstants(self.Values, writer);
        writer.Write(" }");
    }

    private static void EmitCommaSeparatedTypedConstants(
        ImmutableArray<TypedConstant> typedConstants,
        IndentedTextWriter writer)
    {
        foreach ((var i, var typedConstant) in typedConstants.IndicesAndItems())
        {
            EmitTypedConstant(typedConstant, writer);
            if (i != typedConstants.Length - 1)
            {
                writer.Write(", ");
            }
        }
    }

    private static void EmitConstant(
        object? constant,
        ITypeSymbol constantType,
        IndentedTextWriter writer)
    {
        if (constant is null)
        {
            EmitNull(writer);
        }
        else if (constantType.TypeKind is TypeKind.Enum)
        {
            EmitEnumValueFromConstant(constant, (INamedTypeSymbol)constantType, writer);
        }
        else if (constant is char c)
        {
            writer.Write("'");
            writer.Write(c);
            writer.Write("'");
        }
        else if (constant is string str)
        {
            writer.Write(SyntaxFactory.Literal(str).ToString());
        }
        else if (constant is bool b)
        {
            writer.Write(b ? "true" : "false");
        }
        else
        {
            writer.Write(constant);
        }
    }

    private static void EmitEnumValueFromConstant(
        object constant,
        INamedTypeSymbol enumType,
        IndentedTextWriter writer)
    {
        IFieldSymbol matchingField = null!;
        foreach (var member in enumType.GetMembers())
        {
            var field = (IFieldSymbol)member;
            if (object.Equals(field.ConstantValue, constant))
            {
                matchingField = field;
                break;
            }
        }

        writer.Write(enumType.ToFullyQualifiedDisplayString());
        writer.Write(".");
        writer.Write(matchingField.Name);
    }

    private static void EmitTypeTypedConstant(
        TypedConstant typedConstant,
        IndentedTextWriter writer)
    {
        var type = (INamedTypeSymbol)typedConstant.Value!;
        writer.Write("typeof(");
        writer.Write(type.ToFullyQualifiedDisplayString());
        writer.Write(")");
    }

    private static void EmitNull(IndentedTextWriter writer)
    {
        writer.Write("null");
    }

    private static void EmitMethodParameterList(
        IMethodSymbol method,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context,
        bool isForUnsafeAccessor = false)
    {
        writer.Write("(");
        EmitUnparenthesizedParameterList(
            method.Parameters,
            withinType,
            writer,
            context,
            isForUnsafeAccessor);
        writer.Write(")");
    }

    private static void EmitUnparenthesizedParameterList(
        ImmutableArray<IParameterSymbol> parameters,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context,
        bool isForUnsafeAccessor = false)
    {
        foreach ((var i, var parameter) in parameters.IndicesAndItems())
        {
            if (!isForUnsafeAccessor)
            {
                EmitAttributes(parameter, withinType, writer, context, false);
            }

            writer.Write(parameter.Type.ToFullyQualifiedDisplayString());
            writer.Write(" ");

            if (isForUnsafeAccessor)
            {
                writer.Write("a");
                writer.Write(i);
            }
            else
            {
                parameter.WriteVerbatimizedName(writer);
            }

            if (parameter.HasExplicitDefaultValue && !isForUnsafeAccessor)
            {
                writer.Write("= ");
                EmitConstant(parameter.ExplicitDefaultValue, parameter.Type, writer);
            }

            if (i != parameters.Length - 1)
            {
                writer.Write(", ");
            }
        }
    }

    /*private static void EmitUnparenthesizedArgumentListFromMethodParameters(
        IMethodSymbol method,
        IndentedTextWriter writer,
        bool isForUnsafeAccessor = false)
    {
        EmitUnparenthesizedArgumentListFromParameters(
            method.Parameters,
            writer,
            isForUnsafeAccessor);
    }*/

    private static void EmitUnparenthesizedArgumentListFromParameters(
        ImmutableArray<IParameterSymbol> parameters,
        IndentedTextWriter writer)
    {
        foreach ((var i, var parameter) in parameters.IndicesAndItems())
        {
            var refKindModifier = parameter.RefKind.ToCSharpString();
            if (refKindModifier is not null)
            {
                writer.Write(refKindModifier);
                writer.Write(" ");
            }

            parameter.WriteVerbatimizedName(writer);

            if (i != parameters.Length - 1)
            {
                writer.Write(", ");
            }
        }
    }

    private static void EmitFeatureInheritance(
        InternalFeatureSymbol feature,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        EmitAttributes(feature.RoslynSymbol, withinType, writer, context, true);
        if (feature is not InternalFieldSymbol
            && feature.RoslynSymbol.DeclaredAccessibility is Accessibility.Public
            && feature.RoslynSymbol.IsVirtual
            && !feature.RoslynSymbol.IsAbstract)
        {
            writer.Write("[");
#pragma warning disable CS0618
            writer.Write(typeof(InterfaceInheritanceDevirtualizeAttribute).GloballyQualifiedName());
#pragma warning restore CS0618
            writer.Write("]");
            writer.WriteLine();
        }
        EmitMainModifiers(feature.RoslynSymbol, writer);
        if (feature.HasOverrideAttribute)
        {
            writer.Write(" override");
        }

        writer.Write(" ");

        switch (feature)
        {
            case InternalPropertySymbol property:
                EmitPropertyInheritanceCore(property, declaringType, withinType, writer, context);
                break;
            case InternalFieldSymbol field:
                EmitFieldInheritanceCore(field, declaringType, withinType, writer, context);
                break;
            case InternalEventSymbol @event:
                EmitEventInheritanceCore(@event, declaringType, withinType, writer, context);
                break;
            case InternalMethodSymbol method:
                EmitMethodInheritanceCore(method, declaringType, withinType, writer, context);
                break;
        }
    }

    private static void EmitFeatureLocationExpression(
        InternalFeatureSymbol feature,
        INamedTypeSymbol declaringType,
        IndentedTextWriter writer)
    {
        if (feature.RoslynSymbol.IsStatic)
        {
            writer.Write(declaringType.ToFullyQualifiedDisplayString());
        }
        else
        {
            writer.Write("((");
            writer.Write(declaringType.ToFullyQualifiedDisplayString());
            writer.Write(")this)");
        }
    }

    private static void EmitPropertyInheritanceCore(
        InternalPropertySymbol property,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        writer.Write(property.RoslynSymbol.Type.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        if (property.RoslynSymbol.IsIndexer)
        {
            writer.Write("this[");
            EmitUnparenthesizedParameterList(
                property.RoslynSymbol.Parameters,
                withinType,
                writer,
                context);
            writer.Write("]");
        }
        else
        {
            writer.Write(property.RoslynSymbol.Name);
        }
        writer.WriteLine();

        writer.WriteBracedSectionStart();

        if (property.RoslynSymbol.GetMethod is not null)
        {
            EmitAttributes(property.RoslynSymbol.GetMethod, withinType, writer, context, false);
            writer.Write("get");
            writer.WriteLine();

            writer.WriteBracedSectionStart();

            if (property.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
            {
                EmitUnsafeGetterForProperty(property.RoslynSymbol, declaringType, writer);
            }

            writer.Write("return ");

            if (property.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
            {
                EmitUnsafeGetterInvocationForProperty(property.RoslynSymbol, writer, "this");
            }
            else
            {
                EmitAccessExpressionForPropertyInheritance(property, declaringType, writer);
            }

            writer.Write(";");
            writer.WriteLine();

            writer.WriteBracedSectionEnd();
        }

        if (property.RoslynSymbol.SetMethod is not null
            && property.RoslynSymbol.SetMethod.DeclaredAccessibility is not Accessibility.Private)
        {
            EmitAttributes(property.RoslynSymbol.SetMethod, withinType, writer, context, false);
            EmitAccessibilityModifiersForPropertyAccessor(
                property.RoslynSymbol.SetMethod,
                property.RoslynSymbol,
                writer);
            writer.Write("set");
            writer.WriteLine();

            writer.WriteBracedSectionStart();

            if (property.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
            {
                EmitUnsafeSetterForProperty(property.RoslynSymbol, declaringType, writer);
                EmitUnsafeSetterInvocationForProperty(property.RoslynSymbol, writer, "this");
            }
            else
            {
                EmitAccessExpressionForPropertyInheritance(property, declaringType, writer);
                writer.Write(" = value");
            }

            writer.Write(";");
            writer.WriteLine();

            writer.WriteBracedSectionEnd();
        }

        writer.WriteBracedSectionEnd();
    }

    private static void EmitAccessExpressionForPropertyInheritance(
        InternalPropertySymbol property,
        INamedTypeSymbol declaringType,
        IndentedTextWriter writer)
    {
        EmitFeatureLocationExpression(property, declaringType, writer);

        if (property.RoslynSymbol.IsIndexer)
        {
            writer.Write("[");
            EmitUnparenthesizedArgumentListFromParameters(property.RoslynSymbol.Parameters, writer);
            writer.Write("]");
        }
        else
        {
            writer.Write(".");
            writer.Write(property.RoslynSymbol.Name);
        }
    }

    private static void EmitAccessibilityModifiersForPropertyAccessor(
        IMethodSymbol accessor,
        IPropertySymbol property,
        IndentedTextWriter writer)
    {
        if (accessor.DeclaredAccessibility == property.DeclaredAccessibility)
        {
            return;
        }

        if (accessor.DeclaredAccessibility is Accessibility.Protected)
        {
            writer.Write("protected");
        }
        else if (accessor.DeclaredAccessibility is Accessibility.Internal)
        {
            writer.Write("internal");
        }
        else if (accessor.DeclaredAccessibility is Accessibility.Private)
        {
            writer.Write("private");
        }
        else if (accessor.DeclaredAccessibility is Accessibility.ProtectedOrInternal)
        {
            writer.Write("protected internal");
        }
        else if (accessor.DeclaredAccessibility is Accessibility.ProtectedAndInternal)
        {
            writer.Write("private protected");
        }

        writer.Write(" ");
    }

    private static void EmitFieldInheritanceCore(
        InternalFieldSymbol field,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        if (field.RoslynSymbol.IsReadOnly)
        {
            writer.Write("readonly ");
        }
        else if (field.RoslynSymbol.IsConst)
        {
            writer.Write("const ");
        }
        writer.Write(field.RoslynSymbol.Type.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        writer.Write(field.RoslynSymbol.Name);
        writer.Write(" = ");

        if (field.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
        {
            if (field.RoslynSymbol.IsConst)
            {
                EmitConstant(field.RoslynSymbol.ConstantValue, field.RoslynSymbol.Type, writer);
            }
            else
            {
                field.RoslynSymbol.WriteUnsafeAccessorName(writer);
                writer.Write("(null!)");
            }
        }
        else
        {
            EmitFeatureLocationExpression(field, declaringType, writer);
            writer.Write(".");
            writer.Write(field.RoslynSymbol.Name);
        }

        writer.Write(";");
        writer.WriteLine();

        if (field.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
        {
            EmitUnsafeAccessorForField(field.RoslynSymbol, declaringType, writer);
        }
    }

    private static void EmitEventInheritanceCore(
        InternalEventSymbol @event,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        writer.Write("event ");
        writer.Write(@event.RoslynSymbol.Type.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        writer.Write(@event.RoslynSymbol.Name);
        writer.WriteLine();

        writer.WriteBracedSectionStart();

        if (@event.RoslynSymbol.AddMethod is not null)
        {
            EmitAttributes(@event.RoslynSymbol.AddMethod, withinType, writer, context, false);
            writer.Write("add");
            writer.WriteLine();

            writer.WriteBracedSectionStart();

            if (@event.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
            {
                EmitUnsafeAddMethodForEvent(@event.RoslynSymbol, declaringType, writer);
                EmitUnsafeAddMethodInvocationForEvent(@event.RoslynSymbol, writer, "this");
            }
            else
            {
                EmitFeatureLocationExpression(@event, declaringType, writer);
                writer.Write(".");
                writer.Write(@event.RoslynSymbol.Name);
                writer.Write(" += value");
            }

            writer.Write(";");
            writer.WriteLine();

            writer.WriteBracedSectionEnd();
        }

        if (@event.RoslynSymbol.RemoveMethod is not null)
        {
            EmitAttributes(@event.RoslynSymbol.RemoveMethod, withinType, writer, context, false);
            writer.Write("remove");
            writer.WriteLine();

            writer.WriteBracedSectionStart();

            if (@event.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
            {
                EmitUnsafeRemoveMethodForEvent(@event.RoslynSymbol, declaringType, writer);
                EmitUnsafeRemoveMethodInvocationForEvent(@event.RoslynSymbol, writer, "this");
            }
            else
            {
                EmitFeatureLocationExpression(@event, declaringType, writer);
                writer.Write(".");
                writer.Write(@event.RoslynSymbol.Name);
                writer.Write(" -= value");
            }

            writer.Write(";");
            writer.WriteLine();

            writer.WriteBracedSectionEnd();
        }

        writer.WriteBracedSectionEnd();
    }

    private static void EmitMethodInheritanceCore(
        InternalMethodSymbol method,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        EmitMethodCoreSignature(method.RoslynSymbol, declaringType, withinType, writer, context);
        writer.WriteLine();

        writer.WriteBracedSectionStart();

        if (method.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
        {
            EmitUnsafeAccessorForMethod(method.RoslynSymbol, declaringType, writer);
        }

        if (!method.RoslynSymbol.ReturnsVoid)
        {
            writer.Write("return ");
        }

        if (method.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
        {
            writer.Write(method.RoslynSymbol.Name);
            //method.RoslynSymbol.WriteUnsafeAccessorName(writer);
            EmitTypeParameterList(method.RoslynSymbol.TypeParameters, writer);
            writer.Write("(");
            if (method.RoslynSymbol.IsStatic)
            {
                writer.Write("null!");
            }
            else
            {
                writer.Write("this");
            }

            if (method.RoslynSymbol.Parameters.Length > 0)
            {
                writer.Write(", ");
                EmitUnparenthesizedArgumentListFromParameters(method.RoslynSymbol.Parameters, writer);
            }
            writer.Write(")");
        }
        else
        {
            EmitFeatureLocationExpression(method, declaringType, writer);
            writer.Write(".");
            writer.Write(method.RoslynSymbol.Name);
            EmitTypeParameterList(method.RoslynSymbol.TypeParameters, writer);
            writer.Write("(");
            EmitUnparenthesizedArgumentListFromParameters(method.RoslynSymbol.Parameters, writer);
            writer.Write(")");
        }

        writer.Write(";");
        writer.WriteLine();

        writer.WriteBracedSectionEnd();
    }

    private static void EmitMethodCoreSignature(
        IMethodSymbol method,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context,
        bool isForUnsafeAccessor = false)
    {
        writer.Write(method.ReturnType.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        /*if (isForUnsafeAccessor)
        {
            method.WriteUnsafeAccessorName(writer);
        }
        else
        {*/
        writer.Write(method.Name);
        //}
        EmitTypeParameterList(method.TypeParameters, writer);
        writer.Write("(");
        if (isForUnsafeAccessor)
        {
            writer.Write(declaringType.ToFullyQualifiedDisplayString());
            writer.Write(" c");
            if (method.Parameters.Length > 0)
            {
                writer.Write(", ");
            }
        }
        EmitUnparenthesizedParameterList(
            method.Parameters,
            withinType,
            writer,
            context,
            isForUnsafeAccessor);
        writer.Write(")");

        foreach (var typeParameter in method.TypeParameters)
        {
            if (!typeParameter.HasConstraints()) continue;

            writer.WriteLine();

            // @todo: EnumerableExtensions.WithLastFlag

            writer.Indent++;

            writer.Write("where ");
            writer.Write(typeParameter.Name);
            writer.Write(" : ");

            var constraintStrings = EnumerateConstraintStrings(typeParameter).ToArray();
            foreach ((var j, var constraintString) in constraintStrings.IndicesAndItems())
            {
                writer.Write(constraintString);
                if (j != constraintStrings.Length - 1)
                {
                    writer.Write(", ");
                }
            }

            writer.Indent--;
        }
    }

    private static IEnumerable<string> EnumerateConstraintStrings(
        ITypeParameterSymbol typeParameter)
    {
        if (typeParameter.HasReferenceTypeConstraint)
        {
            if (typeParameter.ReferenceTypeConstraintNullableAnnotation is NullableAnnotation.Annotated)
            {
                yield return "class?";
            }
            else
            {
                yield return "class";
            }
        }

        if (typeParameter.HasValueTypeConstraint && !typeParameter.HasUnmanagedTypeConstraint)
        {
            yield return "struct";
        }

        if (typeParameter.HasUnmanagedTypeConstraint)
        {
            yield return "unmanaged";
        }

        if (typeParameter.HasNotNullConstraint)
        {
            yield return "notnull";
        }

        foreach (var constraintType in typeParameter.ConstraintTypes)
        {
            yield return constraintType.ToFullyQualifiedDisplayString();
        }

        if (typeParameter.HasConstructorConstraint)
        {
            yield return "new()";
        }
    }

    private static void EmitTypeParameterList(
        ImmutableArray<ITypeParameterSymbol> typeParameters,
        IndentedTextWriter writer)
    {
        if (typeParameters.Length == 0)
        {
            return;
        }

        writer.Write("<");
        foreach ((var i, var typeParameter) in typeParameters.IndicesAndItems())
        {
            writer.Write(typeParameter.Name);
            if (i != typeParameters.Length - 1)
            {
                writer.Write(", ");
            }
        }
        writer.Write(">");
    }

    private static void EmitDataClassPropertyProxy(
        IPropertySymbol property,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        EmitAttributes(property, withinType, writer, context, true);
        EmitMainModifiers(
            property,
            writer,
            includeSealed: !property.IsVirtual && property.DeclaredAccessibility is not Accessibility.Private);
        writer.Write(" ");
        writer.Write(property.Type.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        writer.Write(property.Name);
        writer.WriteLine();

        writer.WriteBracedSectionStart();

        if (property.GetMethod is not null)
        {
            EmitAttributes(property.GetMethod, withinType, writer, context, false);
            writer.Write("get");
            writer.WriteLine();

            writer.WriteBracedSectionStart();

            if (!property.IsPublicOrInternal())
            {
                EmitUnsafeGetterForProperty(property, property.ContainingType, writer);
            }

            writer.Write("return ");
            if (property.IsPublicOrInternal())
            {
                writer.Write(GeneratedInterfaceDataPropertyName);
                writer.Write(".");
                writer.Write(property.Name);
            }
            else
            {
                EmitUnsafeGetterInvocationForProperty(
                    property,
                    writer,
                    GeneratedInterfaceDataPropertyName);
            }

            writer.Write(";");
            writer.WriteLine();

            writer.WriteBracedSectionEnd();
        }

        if (property.SetMethod is not null)
        {
            EmitAttributes(property.SetMethod, withinType, writer, context, false);
            EmitAccessibilityModifiersForPropertyAccessor(property.SetMethod, property, writer);
            writer.Write("set");
            writer.WriteLine();

            writer.WriteBracedSectionStart();

            if (property.IsPublicOrInternal())
            {
                writer.Write(GeneratedInterfaceDataPropertyName);
                writer.Write(".");
                writer.Write(property.Name);
                writer.Write(" = value");
            }
            else
            {
                EmitUnsafeSetterForProperty(property, property.ContainingType, writer);
                EmitUnsafeSetterInvocationForProperty(
                    property,
                    writer,
                    GeneratedInterfaceDataPropertyName);
            }

            writer.Write(";");
            writer.WriteLine();

            writer.WriteBracedSectionEnd();
        }

        writer.WriteBracedSectionEnd();
    }

    private static void EmitDataClassEventProxy(
        IEventSymbol @event,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        EmitAttributes(@event, withinType, writer, context, true);
        EmitMainModifiers(
            @event,
            writer,
            includeSealed: !@event.IsVirtual && @event.DeclaredAccessibility is not Accessibility.Private);
        writer.Write(" event ");
        writer.Write(@event.Type.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        writer.Write(@event.Name);
        writer.WriteLine();

        writer.WriteBracedSectionStart();

        if (@event.AddMethod is not null)
        {
            EmitAttributes(@event.AddMethod, withinType, writer, context, false);
            writer.Write("add");
            writer.WriteLine();

            writer.WriteBracedSectionStart();

            if (@event.IsPublicOrInternal())
            {
                writer.Write(GeneratedInterfaceDataPropertyName);
                writer.Write(".");
                writer.Write(@event.Name);
                writer.Write(" += value");
            }
            else
            {
                EmitUnsafeAddMethodForEvent(@event, @event.ContainingType, writer);
                EmitUnsafeAddMethodInvocationForEvent(
                    @event,
                    writer,
                    GeneratedInterfaceDataPropertyName);
            }

            writer.Write(";");
            writer.WriteLine();

            writer.WriteBracedSectionEnd();
        }

        if (@event.RemoveMethod is not null)
        {
            EmitAttributes(@event.RemoveMethod, withinType, writer, context, false);
            writer.Write("remove");
            writer.WriteLine();

            writer.WriteBracedSectionStart();

            if (@event.IsPublicOrInternal())
            {
                writer.Write(GeneratedInterfaceDataPropertyName);
                writer.Write(".");
                writer.Write(@event.Name);
                writer.Write(" -= value");
            }
            else
            {
                EmitUnsafeRemoveMethodForEvent(@event, @event.ContainingType, writer);
                EmitUnsafeRemoveMethodInvocationForEvent(
                    @event,
                    writer,
                    GeneratedInterfaceDataPropertyName);
            }

            writer.Write(";");
            writer.WriteLine();

            writer.WriteBracedSectionEnd();
        }

        writer.WriteBracedSectionEnd();
    }

    private static void EmitUnsafeGetterForProperty(
        IPropertySymbol property,
        INamedTypeSymbol declaringType,
        IndentedTextWriter writer)
    {
        writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind.");
        if (property.IsStatic)
        {
            writer.Write("Static");
        }
        writer.Write("Method, Name=\"");
        writer.Write(property.GetMethod!.Name);
        writer.Write("\")]");
        writer.WriteLine();
        writer.Write("extern static ");
        writer.Write(property.Type.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        writer.Write(property.GetMethod!.Name);
        writer.Write("(");
        writer.Write(declaringType.ToFullyQualifiedDisplayString());
        writer.Write(" c");
        if (property.IsIndexer)
        {
            writer.Write(", ");
            EmitUnparenthesizedParameterList(
                property.Parameters,
                null!,
                writer,
                null!,
                isForUnsafeAccessor: true);
        }
        writer.Write(");");
        writer.WriteLine();
    }

    private static void EmitUnsafeSetterForProperty(
        IPropertySymbol property,
        INamedTypeSymbol declaringType,
        IndentedTextWriter writer)
    {
        writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind.");
        if (property.IsStatic)
        {
            writer.Write("Static");
        }
        writer.Write("Method, Name=\"");
        writer.Write(property.SetMethod!.Name);
        writer.Write("\")]");
        writer.WriteLine();
        writer.Write("extern static void ");
        writer.Write(property.SetMethod!.Name);
        writer.Write("(");
        writer.Write(declaringType.ToFullyQualifiedDisplayString());
        writer.Write(" c");
        if (property.IsIndexer)
        {
            writer.Write(", ");
            EmitUnparenthesizedParameterList(
                property.Parameters,
                null!,
                writer,
                null!,
                isForUnsafeAccessor: true);
        }
        writer.Write(", ");
        writer.Write(property.Type.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        writer.Write("v);");
        writer.WriteLine();
    }

    private static void EmitUnsafeGetterInvocationForProperty(
        IPropertySymbol property,
        IndentedTextWriter writer,
        string targetString)
    {
        writer.Write(property.GetMethod!.Name);
        writer.Write("(");
        if (property.IsStatic)
        {
            writer.Write("null!");
        }
        else
        {
            writer.Write(targetString);
        }

        if (property.IsIndexer)
        {
            writer.Write(", ");
            EmitUnparenthesizedArgumentListFromParameters(
                property.Parameters,
                writer);
        }

        writer.Write(")");
    }

    private static void EmitUnsafeSetterInvocationForProperty(
        IPropertySymbol property,
        IndentedTextWriter writer,
        string targetString)
    {
        writer.Write(property.SetMethod!.Name);
        writer.Write("(");
        if (property.IsStatic)
        {
            writer.Write("null!");
        }
        else
        {
            writer.Write(targetString);
        }

        if (property.IsIndexer)
        {
            writer.Write(", ");
            EmitUnparenthesizedArgumentListFromParameters(
                property.Parameters,
                writer);
        }

        writer.Write(", value)");
    }

    private static void EmitUnsafeAddMethodForEvent(
        IEventSymbol @event,
        INamedTypeSymbol declaringType,
        IndentedTextWriter writer)
    {
        writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind.");
        if (@event.IsStatic)
        {
            writer.Write("Static");
        }
        writer.Write("Method, Name=\"");
        writer.Write(@event.AddMethod!.Name);
        writer.Write("\")]");
        writer.WriteLine();
        writer.Write("extern static void ");
        writer.Write(@event.AddMethod!.Name);
        writer.Write("(");
        writer.Write(declaringType.ToFullyQualifiedDisplayString());
        writer.Write(" c, ");
        writer.Write(@event.Type.ToFullyQualifiedDisplayString());
        writer.Write(" h);");
        writer.WriteLine();
    }

    private static void EmitUnsafeRemoveMethodForEvent(
        IEventSymbol @event,
        INamedTypeSymbol declaringType,
        IndentedTextWriter writer)
    {
        writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind.");
        if (@event.IsStatic)
        {
            writer.Write("Static");
        }
        writer.Write("Method, Name=\"");
        writer.Write(@event.RemoveMethod!.Name);
        writer.Write("\")]");
        writer.WriteLine();
        writer.Write("extern static void ");
        writer.Write(@event.RemoveMethod!.Name);
        writer.Write("(");
        writer.Write(declaringType.ToFullyQualifiedDisplayString());
        writer.Write(" c, ");
        writer.Write(@event.Type.ToFullyQualifiedDisplayString());
        writer.Write(" h);");
        writer.WriteLine();
    }

    private static void EmitUnsafeAddMethodInvocationForEvent(
        IEventSymbol @event,
        IndentedTextWriter writer,
        string targetString)
    {
        writer.Write(@event.AddMethod!.Name);
        writer.Write("(");
        if (@event.IsStatic)
        {
            writer.Write("null!");
        }
        else
        {
            writer.Write(targetString);
        }

        writer.Write(", value)");
    }

    private static void EmitUnsafeRemoveMethodInvocationForEvent(
        IEventSymbol @event,
        IndentedTextWriter writer,
        string targetString)
    {
        writer.Write(@event.RemoveMethod!.Name);
        writer.Write("(");
        if (@event.IsStatic)
        {
            writer.Write("null!");
        }
        else
        {
            writer.Write(targetString);
        }

        writer.Write(", value)");
    }

    private static void EmitUnsafeAccessorForField(
        IFieldSymbol field,
        INamedTypeSymbol declaringType,
        IndentedTextWriter writer)
    {
        writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind.");
        if (field.IsStatic)
        {
            writer.Write("Static");
        }
        writer.Write("Field, Name=\"");
        writer.Write(field.Name);
        writer.Write("\")]");
        writer.WriteLine();
        writer.Write("private extern static ref ");
        writer.Write(field.Type.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        field.WriteUnsafeAccessorName(writer);
        writer.Write("(");
        writer.Write(declaringType.ToFullyQualifiedDisplayString());
        writer.Write(" c);");
        writer.WriteLine();
    }

    private static void EmitUnsafeAccessorForMethod(
        IMethodSymbol method,
        INamedTypeSymbol declaringType,
        IndentedTextWriter writer)
    {
        writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind.");
        if (method.IsStatic)
        {
            writer.Write("Static");
        }
        writer.Write("Method, Name=\"");
        writer.Write(method.Name);
        writer.Write("\")]");
        writer.WriteLine();
        writer.Write("extern static ");
        EmitMethodCoreSignature(
            method,
            declaringType,
            null!,
            writer,
            null!,
            isForUnsafeAccessor: true);
        writer.Write(";");
        writer.WriteLine();
    }
}
