using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;
using Franzo.Essentials.Roslyn;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Franzo.Essentials.InterfaceInheritance.Generator;

public partial class InterfaceInheritanceGenerator : IIncrementalGenerator
{
    internal static void Emit(Context context)
    {
        var sb = new StringBuilder();
        var writer = new IndentedTextWriter(new StringWriter(sb), "    ");

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine();
        writer.WriteLine("#nullable restore annotations");
        writer.WriteLine("#nullable disable warnings");
        writer.WriteLine("#nullable disable warnings");
        writer.WriteLine("#pragma warning disable CS0108");
        writer.WriteLine();

        foreach (var type in context.AnalysisData.RootTypesToEmit)
        {
            EmitTypeWithNamespaceDeclaration(type, writer, context);
        }

        context.SourceProductionContext.AddSource(
            "Franzo.Essentials.InterfaceInheritance.Generated.cs",
            sb.ToString());
    }

    internal static void EmitTypeWithNamespaceDeclaration(
        InternalTypeSymbol type,
        IndentedTextWriter writer,
        Context context)
    {
        writer.Write("namespace ");
        writer.Write(type.RoslynSymbol.ContainingNamespace.ToDisplayString());
        writer.WriteLine();
        writer.WriteBracedSectionStart();

        EmitType(type, writer, context);

        writer.WriteBracedSectionEnd();
        writer.WriteLine();
    }

    private static void EmitTypes(
        IEnumerable<InternalTypeSymbol> types,
        IndentedTextWriter writer,
        Context context)
    {
        foreach (var type in types)
        {
            EmitType(type, writer, context);
        }
    }

    private static void EmitType(
        InternalTypeSymbol type,
        IndentedTextWriter writer,
        Context context)
    {
        writer.Write("partial");

        if (type.RoslynSymbol.TypeKind is TypeKind.Interface)
        {
            writer.Write($" interface");
        }
        else
        {
            if (type.RoslynSymbol.IsRecord)
            {
                writer.Write(" record");
            }

            writer.Write(" ");
            writer.Write(type.RoslynSymbol.TypeKind is TypeKind.Class ? "class" : "struct");
        }

        writer.Write(" ");
        writer.Write(type.RoslynSymbol.Name);

        if (type.IsDataClass)
        {
            writer.Write(" : ");
            writer.Write(typeof(InterfaceData).GloballyQualifiedName());
            writer.Write("<");
            writer.Write(type.ContainingType!.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(">");
        }
        else if (type.RoslynSymbol.TypeKind.IsClassOrStruct())
        {
            if (type.AttributeSpecifiedDirectInterfaces.Count > 0)
            {
                writer.Write(" : ");
                foreach ((var i, var @interface) in type.AttributeSpecifiedDirectInterfaces.IndicesAndItems())
                {
                    writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
                    if (i != type.AttributeSpecifiedDirectInterfaces.Count - 1)
                    {
                        writer.Write(", ");
                    }
                }
            }
        }

        writer.WriteLine();
        writer.WriteBracedSectionStart();

        if (type.IsDataClass)
        {
            writer.Write("public static readonly global::System.Reflection.ConstructorInfo ");
            writer.Write(GeneratedConstructorPropertyName);
            writer.Write(" = typeof(");
            writer.Write(type.RoslynSymbol.ToDisplayString());
            writer.Write(").GetConstructors()[0];");
            writer.WriteLine();
        }

        if (type.RoslynSymbol.TypeKind.IsClassOrStruct())
        {
            if (!type.IsDataClass)
            {
                EmitRealDataFieldsAndDataPropertyImplementations(type, writer, context);
            }

            EmitFakeDataFieldsAndConstructors(type, writer, context);
        }

        if (type.DataClass is not null)
        {
            foreach (var property in type.DataClass.DeclaredProperties)
            {
                EmitDataClassPropertyProxy(
                    property.RoslynSymbol,
                    type.RoslynSymbol,
                    writer,
                    context);
            }

            writer.Write("public ");
            writer.Write(type.DataClass.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(" ");
            writer.Write(GeneratedInterfaceDataPropertyName);
            writer.Write(" { get; }");
            writer.WriteLine();
        }

        foreach (var @interface in type.InterfacesInheriting)
        {
            foreach (var feature in @interface.DeclaredFeatures)
            {
                if (!feature.RoslynSymbol.IsAccessibleFromType(
                        type.RoslynSymbol,
                        context.Compilation)
                    || feature.RoslynSymbol is IMethodSymbol
                    {
                        MethodKind: MethodKind.EventAdd or MethodKind.EventRemove
                    })
                {
                    continue;
                }

                foreach (var shadowingType in feature.TypesDeclaringShadowingFeatures)
                {
                    if (type.RoslynSymbol.IsAssignableTo(
                            shadowingType.RoslynSymbol,
                            context.Compilation)
                        || type.AttributeSpecifiedDirectInterfaces.Any(
                            i => i.RoslynSymbol.IsAssignableTo(
                                shadowingType.RoslynSymbol,
                                context.Compilation)))
                    {
                        continue;
                    }
                }

                EmitFeatureInheritance(
                    feature,
                    @interface.RoslynSymbol,
                    type.RoslynSymbol,
                    writer,
                    context);
            }
        }

        foreach (var @interface in type.DirectInterfaces)
        {
            EmitAsInterfaceMethod(@interface, writer, context);
        }

        foreach (var memberType in type.DeclaredTypes)
        {
            EmitType(memberType, writer, context);
        }

        writer.WriteBracedSectionEnd();
    }

    private static void EmitRealDataFieldsAndDataPropertyImplementations(
        InternalTypeSymbol type,
        IndentedTextWriter writer,
        Context context)
    {
        var x = type.InterfacesInheriting.ToArray();
        foreach (var @interface in type.InterfacesInheriting)
        {
            if (@interface.DataClass is null) continue;

            writer.Write("private ");
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write(" ");
            EmitRealDataFieldName(@interface, writer);
            writer.WriteLine();

            writer.Indent++;
            writer.Write("= (");
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write(")global::System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(typeof(");
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write("));");
            writer.WriteLine();
            writer.Indent--;
        }

        foreach (var @interface in type.InterfacesInheriting)
        {
            if (@interface.DataClass is null) continue;

            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write(" ");
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(GeneratedInterfaceDataPropertyName);
            writer.WriteLine();

            writer.WriteBracedSectionStart();
            writer.Write("get => ");
            EmitRealDataFieldName(@interface, writer);
            writer.Write(";");
            writer.WriteLine();
            writer.WriteBracedSectionEnd();
        }
    }

    private static void EmitAsInterfaceMethod(
        InternalTypeSymbol @interface,
        IndentedTextWriter writer,
        Context context)
    {
        writer.Write("private ");
        writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
        writer.Write(" As");
        writer.Write(@interface.RoslynSymbol.Name.WithoutInterfaceI());
        writer.Write("()");
        writer.WriteLine();
        writer.WriteBracedSectionStart();
        writer.WriteLine("return this;");
        writer.WriteBracedSectionEnd();
    }

    private static void EmitFakeDataFieldsAndConstructors(
        InternalTypeSymbol type,
        IndentedTextWriter writer,
        Context context)
    {
        var anchorType = type;
        if (type.IsDataClass)
        {
            anchorType = type.ContainingType!;
        }

        foreach (var @interface in anchorType.DirectInterfaces)
        {
            if (@interface.DataClass is null) continue;

            writer.Write("private ");
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write(" ");
            EmitFakeDataFieldName(@interface, writer);
            writer.Write(";");
            writer.WriteLine();
        }

        foreach (var @interface in anchorType.DirectInterfaces)
        {
            if (@interface.DataClass is null) continue;

            writer.Write("private ");
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write(" Construct");
            writer.Write(@interface.RoslynSymbol.Name.WithoutInterfaceI());
            EmitMethodParameterList(
                @interface.DataClass.ConstructorIfDataClass!.RoslynSymbol,
                type.RoslynSymbol,
                writer,
                context);
            writer.WriteLine();
            writer.WriteBracedSectionStart();

            writer.Write("if (");
            if (type.IsDataClass)
            {
                writer.Write("((");
                writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
                writer.Write(")");
                writer.Write(nameof(InterfaceData<object>.This));
                writer.Write(").");
                writer.Write(GeneratedInterfaceDataPropertyName);
            }
            else
            {
                EmitRealDataFieldName(@interface, writer);
            }
            writer.Write(".");
            writer.Write(nameof(InterfaceData.__IsConstructed));
            writer.Write(") return null!;");
            writer.WriteLine();

            if (!type.IsDataClass)
            {
                foreach (var ancestorInterface in @interface.SelfAndInterfaces)
                {
                    if (ancestorInterface.DataClass is null) continue;

                    EmitRealDataFieldName(ancestorInterface, writer);
                    writer.Write(".");
                    writer.Write(nameof(InterfaceData<object>.__This));
                    writer.Write(" = this;");
                    writer.WriteLine();
                }
            }

            // @todo: remove string interpolations if needed for perf

            // @todo: create delegate and invoke that instead
            writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
            writer.Write(".");
            writer.Write(InterfaceDataClassName);
            writer.Write(".");
            writer.Write(GeneratedConstructorPropertyName);
            writer.Write(".Invoke(");
            if (type.IsDataClass)
            {
                writer.Write("((");
                writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
                writer.Write(")");
                writer.Write(nameof(InterfaceData<object>.This));
                writer.Write(").");
                writer.Write(GeneratedInterfaceDataPropertyName);
            }
            else
            {
                EmitRealDataFieldName(@interface, writer);
            }
            writer.Write(", new object?[] { ");
            EmitUnparenthesizedArgumentListFromMethodParameters(
                @interface.DataClass.ConstructorIfDataClass.RoslynSymbol,
                writer);
            writer.Write(" });");
            writer.WriteLine();

            writer.WriteLine($"return null!;");

            writer.WriteBracedSectionEnd();
        }
    }

    private static void EmitFakeDataFieldName(
        InternalTypeSymbol @interface,
        IndentedTextWriter writer)
    {
        writer.Write(@interface.RoslynSymbol.Name.WithoutInterfaceI());
        writer.Write("Data");
    }

    private static void EmitRealDataFieldName(
        InternalTypeSymbol @interface,
        IndentedTextWriter writer)
    {
        writer.Write("__");
        EmitFakeDataFieldName(@interface, writer);
    }

    private static void EmitMainModifiers(
        ISymbol symbol,
        IndentedTextWriter writer,
        bool includeSealed)
    {
        EmitAccessibilityModifiers(symbol.DeclaredAccessibility, writer);

        if (includeSealed)
        {
            writer.Write(" sealed");
        }

        if (symbol.IsStatic && symbol is not IFieldSymbol { IsConst: true })
        {
            writer.Write(" static");
        }
    }

    private static void EmitAccessibilityModifiers(
        Accessibility accessibility,
        IndentedTextWriter writer)
    {
        if (accessibility is Accessibility.Public)
        {
            writer.Write("public");
        }
        else if (accessibility is Accessibility.Protected)
        {
            writer.Write("protected");
        }
        else if (accessibility is Accessibility.Internal)
        {
            writer.Write("internal");
        }
        else if (accessibility is Accessibility.Private)
        {
            writer.Write("private");
        }
        else if (accessibility is Accessibility.ProtectedOrInternal)
        {
            writer.Write("protected internal");
        }
        else if (accessibility is Accessibility.ProtectedAndInternal)
        {
            writer.Write("private protected");
        }
    }

    private static void EmitAttributes(
        ISymbol symbol,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context,
        bool separateLines)
    {
        var attributes = symbol.GetAttributes();
        // Note: protected/private protected member types in a interface CAN currently be accessed by implementing classes
        foreach ((var i, var attribute) in attributes.IndicesAndItems())
        {
            if (attribute.AttributeClass is null
                || attribute.AttributeClass.IsCompilerGeneratedAttributeType()
                || !attribute.AttributeClass.IsAccessibleFromType(withinType, context.Compilation)
                || attribute.AttributeClass.TypeArguments.Any(
                    a => !a.IsAccessibleFromType(withinType, context.Compilation))
                || attribute.ConstructorArguments
                    .Concat(attribute.NamedArguments.Select(p => p.Value))
                    .Any(arg => arg.Kind is TypedConstantKind.Error)
                || attribute.AttributeConstructor is null
                || !attribute.AttributeConstructor.IsAccessibleFromType(withinType, context.Compilation))
            {
                continue;
            }

            EmitAttribute(attribute, writer);

            if (separateLines)
            {
                writer.WriteLine();
            }
            else
            {
                if (i != attributes.Length - 1)
                {
                    writer.Write(" ");
                }
            }
        }
    }

    private static void EmitAttribute(AttributeData attribute, IndentedTextWriter writer)
    {
        writer.Write("[");
        writer.Write(attribute.AttributeClass!.ToFullyQualifiedDisplayString());
        writer.Write("(");

        foreach ((var i, var argument) in attribute.ConstructorArguments.IndicesAndItems())
        {
            EmitTypedConstant(argument, writer);
            if (i != attribute.ConstructorArguments.Length - 1
                || attribute.NamedArguments.Length > 0)
            {
                writer.Write(", ");
            }
        }

        foreach ((var i, var pair) in attribute.NamedArguments.IndicesAndItems())
        {
            writer.Write(pair.Key);
            writer.Write(" = ");
            EmitTypedConstant(pair.Value, writer);
            if (i != attribute.NamedArguments.Length - 1)
            {
                writer.Write(", ");
            }
        }

        writer.Write(")]");
    }

    private static void EmitTypedConstant(TypedConstant typedConstant, IndentedTextWriter writer)
    {
        Debug.Assert(typedConstant.Kind is not TypedConstantKind.Error && typedConstant.Type is not null);

        if (typedConstant.IsNull)
        {
            EmitNull(writer);
        }
        else
        {
            switch (typedConstant.Kind)
            {
                case TypedConstantKind.Array:
                    EmitArrayTypedConstant(typedConstant, writer);
                    break;
                case TypedConstantKind.Primitive or TypedConstantKind.Enum:
                    EmitConstant(typedConstant.Value, typedConstant.Type!, writer);
                    break;
                case TypedConstantKind.Type:
                    EmitTypeTypedConstant(typedConstant, writer);
                    break;
            };
        }
    }

    private static void EmitArrayTypedConstant(TypedConstant self, IndentedTextWriter writer)
    {
        Debug.Assert(self.Type is not null);

        var arrayType = (IArrayTypeSymbol)self.Type!;
        writer.Write("new ");
        writer.Write(arrayType.ElementType.ToFullyQualifiedDisplayString());
        writer.Write("[] { ");
        EmitCommaSeparatedTypedConstants(self.Values, writer);
        writer.Write(" }");
    }

    private static void EmitCommaSeparatedTypedConstants(
        ImmutableArray<TypedConstant> typedConstants,
        IndentedTextWriter writer)
    {
        foreach ((var i, var typedConstant) in typedConstants.IndicesAndItems())
        {
            EmitTypedConstant(typedConstant, writer);
            if (i != typedConstants.Length - 1)
            {
                writer.Write(", ");
            }
        }
    }

    private static void EmitConstant(
        object? constant,
        ITypeSymbol constantType,
        IndentedTextWriter writer)
    {
        // @todo: explicitly disallow structs having InheritInterface
        if (constant is null)
        {
            EmitNull(writer);
        }
        else if (constantType.TypeKind is TypeKind.Enum)
        {
            EmitEnumValueFromConstant(constant, (INamedTypeSymbol)constantType, writer);
        }
        else if (constant is char c)
        {
            writer.Write("'");
            writer.Write(c);
            writer.Write("'");
        }
        else if (constant is string str)
        {
            writer.Write(SyntaxFactory.Literal(str).ToString());
        }
        else
        {
            writer.Write(constant);
        }
    }

    private static void EmitEnumValueFromConstant(
        object constant,
        INamedTypeSymbol enumType,
        IndentedTextWriter writer)
    {
        IFieldSymbol matchingField = null!;
        foreach (var member in enumType.GetMembers())
        {
            var field = (IFieldSymbol)member;
            if (object.Equals(field.ConstantValue, constant))
            {
                matchingField = field;
                break;
            }
        }

        writer.Write(enumType.ToFullyQualifiedDisplayString());
        writer.Write(".");
        writer.Write(matchingField.Name);
    }

    private static void EmitTypeTypedConstant(
        TypedConstant typedConstant,
        IndentedTextWriter writer)
    {
        var type = (INamedTypeSymbol)typedConstant.Value!;
        writer.Write("typeof(");
        writer.Write(type.ToFullyQualifiedDisplayString());
        writer.Write(")");
    }

    private static void EmitNull(IndentedTextWriter writer)
    {
        writer.Write("null");
    }

    private static void EmitMethodParameterList(
        IMethodSymbol method,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        writer.Write("(");
        EmitUnparenthesizedParameterList(method.Parameters, withinType, writer, context);
        writer.Write(")");
    }

    private static void EmitUnparenthesizedParameterList(
        ImmutableArray<IParameterSymbol> parameters,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        foreach ((var i, var parameter) in parameters.IndicesAndItems())
        {
            EmitAttributes(parameter, withinType, writer, context, false);
            writer.Write(parameter.Type.ToFullyQualifiedDisplayString());
            writer.Write(" ");
            parameter.WriteVerbatimizedName(writer);

            if (parameter.HasExplicitDefaultValue)
            {
                writer.Write("= ");
                EmitConstant(parameter.ExplicitDefaultValue, parameter.Type, writer);
            }

            if (i != parameters.Length - 1)
            {
                writer.Write(", ");
            }
        }
    }

    private static void EmitUnparenthesizedArgumentListFromMethodParameters(
        IMethodSymbol method,
        IndentedTextWriter writer)
    {
        EmitUnparenthesizedArgumentListFromParameters(method.Parameters, writer);
    }

    private static void EmitUnparenthesizedArgumentListFromParameters(
        ImmutableArray<IParameterSymbol> parameters,
        IndentedTextWriter writer)
    {
        foreach ((var i, var parameter) in parameters.IndicesAndItems())
        {
            var refKindModifier = parameter.RefKind.ToCSharpString();
            if (refKindModifier is not null)
            {
                writer.Write(refKindModifier);
                writer.Write(" ");
            }

            parameter.WriteVerbatimizedName(writer);

            if (i != parameters.Length - 1)
            {
                writer.Write(", ");
            }
        }
    }

    private static void EmitFeatureInheritance(
        InternalFeatureSymbol feature,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        EmitAttributes(feature.RoslynSymbol, withinType, writer, context, true);
        EmitMainModifiers(feature.RoslynSymbol, writer, false);
        if (feature.HasOverrideAttribute)
        {
            writer.Write(" override");
        }

        writer.Write(" ");

        switch (feature)
        {
            case InternalPropertySymbol property:
                EmitPropertyInheritanceCore(property, declaringType, withinType, writer, context);
                break;
            case InternalFieldSymbol field:
                EmitFieldInheritanceCore(field, declaringType, withinType, writer, context);
                break;
            case InternalEventSymbol @event:
                EmitEventInheritanceCore(@event, declaringType, withinType, writer, context);
                break;
            case InternalMethodSymbol method:
                EmitMethodInheritanceCore(method, declaringType, withinType, writer, context);
                break;
        }
    }

    private static void EmitFeatureLocationExpression(
        InternalFeatureSymbol feature,
        INamedTypeSymbol declaringType,
        IndentedTextWriter writer)
    {
        if (feature.RoslynSymbol.IsStatic)
        {
            writer.Write(declaringType.ToFullyQualifiedDisplayString());
        }
        else
        {
            writer.Write("((");
            writer.Write(declaringType.ToFullyQualifiedDisplayString());
            writer.Write(")this)");
        }
    }

    private static void EmitPropertyInheritanceCore(
        InternalPropertySymbol property,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        writer.Write(property.RoslynSymbol.Type.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        writer.Write(property.RoslynSymbol.Name);
        if (property.RoslynSymbol.IsIndexer)
        {
            writer.Write("[");
            EmitUnparenthesizedParameterList(
                property.RoslynSymbol.Parameters,
                withinType,
                writer,
                context);
            writer.Write("]");
        }
        writer.WriteLine();

        writer.WriteBracedSectionStart();

        if (property.RoslynSymbol.GetMethod is not null)
        {
            EmitAttributes(property.RoslynSymbol.GetMethod, withinType, writer, context, false);
            writer.Write("get => ");
            EmitAccessExpressionForPropertyInheritance(property, declaringType, writer);
            writer.Write(";");
            writer.WriteLine();
        }

        if (property.RoslynSymbol.SetMethod is not null
            && property.RoslynSymbol.SetMethod.DeclaredAccessibility is not Accessibility.Private)
        {
            EmitAttributes(property.RoslynSymbol.SetMethod, withinType, writer, context, false);
            EmitAccessibilityModifiersForPropertyAccessor(
                property.RoslynSymbol.SetMethod,
                property.RoslynSymbol,
                writer);
            writer.Write("set => ");
            EmitAccessExpressionForPropertyInheritance(property, declaringType, writer);
            writer.Write(" = value;");
            writer.WriteLine();
        }

        writer.WriteBracedSectionEnd();
    }

    private static void EmitAccessExpressionForPropertyInheritance(
        InternalPropertySymbol property,
        INamedTypeSymbol declaringType,
        IndentedTextWriter writer)
    {
        // @todo: should generate proxies for interface data events
        EmitFeatureLocationExpression(property, declaringType, writer);

        if (property.RoslynSymbol.IsIndexer)
        {
            writer.Write("[");
            EmitUnparenthesizedArgumentListFromParameters(property.RoslynSymbol.Parameters, writer);
            writer.Write("]");
        }
        else
        {
            writer.Write(".");
            writer.Write(property.RoslynSymbol.Name);
        }
    }

    private static void EmitAccessibilityModifiersForPropertyAccessor(
        IMethodSymbol accessor,
        IPropertySymbol property,
        IndentedTextWriter writer)
    {
        if (accessor.DeclaredAccessibility == property.DeclaredAccessibility)
        {
            return;
        }

        if (accessor.DeclaredAccessibility is Accessibility.Protected)
        {
            writer.Write("protected");
        }
        else if (accessor.DeclaredAccessibility is Accessibility.Internal)
        {
            writer.Write("internal");
        }
        else if (accessor.DeclaredAccessibility is Accessibility.Private)
        {
            writer.Write("private");
        }
        else if (accessor.DeclaredAccessibility is Accessibility.ProtectedOrInternal)
        {
            writer.Write("protected internal");
        }
        else if (accessor.DeclaredAccessibility is Accessibility.ProtectedAndInternal)
        {
            writer.Write("private protected");
        }
    }

    private static void EmitFieldInheritanceCore(
        InternalFieldSymbol field,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        if (field.RoslynSymbol.IsReadOnly)
        {
            writer.Write("readonly ");
        }
        else if (field.RoslynSymbol.IsConst)
        {
            writer.Write("const ");
        }
        writer.Write(field.RoslynSymbol.Type.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        writer.Write(field.RoslynSymbol.Name);
        writer.Write(" = ");
        EmitFeatureLocationExpression(field, declaringType, writer);
        writer.Write(".");
        writer.Write(field.RoslynSymbol.Name);
        writer.Write(";");
        writer.WriteLine();
    }

    private static void EmitEventInheritanceCore(
        InternalEventSymbol @event,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        writer.Write("event ");
        writer.Write(@event.RoslynSymbol.Type.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        writer.Write(@event.RoslynSymbol.Name);
        writer.WriteLine();

        writer.WriteBracedSectionStart();

        if (@event.RoslynSymbol.AddMethod is not null)
        {
            EmitAttributes(@event.RoslynSymbol.AddMethod, withinType, writer, context, false);
            writer.Write("add => ");
            EmitFeatureLocationExpression(@event, declaringType, writer);
            writer.Write(".");
            writer.Write(@event.RoslynSymbol.Name);
            writer.Write(" += value;");
            writer.WriteLine();
        }

        if (@event.RoslynSymbol.RemoveMethod is not null)
        {
            EmitAttributes(@event.RoslynSymbol.RemoveMethod, withinType, writer, context, false);
            writer.Write("remove => ");
            EmitFeatureLocationExpression(@event, declaringType, writer);
            writer.Write(".");
            writer.Write(@event.RoslynSymbol.Name);
            writer.Write(" -= value;");
            writer.WriteLine();
        }

        writer.WriteBracedSectionEnd();
    }

    private static void EmitMethodInheritanceCore(
        InternalMethodSymbol method,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        writer.Write(method.RoslynSymbol.ReturnType.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        writer.Write(method.RoslynSymbol.Name);
        EmitTypeParameterList(method.RoslynSymbol.TypeParameters, writer);
        EmitMethodParameterList(method.RoslynSymbol, withinType, writer, context);
        writer.WriteLine();

        foreach (var typeParameter in method.RoslynSymbol.TypeParameters)
        {
            if (!typeParameter.HasConstraints()) continue;

            // @todo: EnumerableExtensions.WithLastFlag

            writer.Indent++;

            writer.Write("where ");
            writer.Write(typeParameter.Name);
            writer.Write(" : ");

            var constraintStrings = EnumerateConstraintStrings(typeParameter).ToArray();
            foreach ((var i, var constraintString) in constraintStrings.IndicesAndItems())
            {
                writer.Write(constraintString);
                if (i != constraintStrings.Length - 1)
                {
                    writer.Write(", ");
                }
            }

            writer.WriteLine();
            writer.Indent--;
        }

        writer.WriteBracedSectionStart();

        if (!method.RoslynSymbol.ReturnsVoid)
        {
            writer.Write("return ");
        }
        EmitFeatureLocationExpression(method, declaringType, writer);
        writer.Write(".");
        writer.Write(method.RoslynSymbol.Name);
        EmitTypeParameterList(method.RoslynSymbol.TypeParameters, writer);
        writer.Write("(");
        EmitUnparenthesizedArgumentListFromMethodParameters(method.RoslynSymbol, writer);
        writer.Write(");");
        writer.WriteLine();

        writer.WriteBracedSectionEnd();
    }

    private static IEnumerable<string> EnumerateConstraintStrings(
        ITypeParameterSymbol typeParameter)
    {
        if (typeParameter.HasReferenceTypeConstraint)
        {
            if (typeParameter.ReferenceTypeConstraintNullableAnnotation is NullableAnnotation.Annotated)
            {
                yield return "class?";
            }
            else
            {
                yield return "class";
            }
        }

        if (typeParameter.HasValueTypeConstraint)
        {
            yield return "struct";
        }

        if (typeParameter.HasUnmanagedTypeConstraint)
        {
            yield return "unmanaged";
        }

        if (typeParameter.HasNotNullConstraint)
        {
            yield return "notnull";
        }

        foreach (var constraintType in typeParameter.ConstraintTypes)
        {
            yield return constraintType.ToFullyQualifiedDisplayString();
        }

        if (typeParameter.HasConstructorConstraint)
        {
            yield return "new()";
        }
    }

    private static void EmitTypeParameterList(
        ImmutableArray<ITypeParameterSymbol> typeParameters,
        IndentedTextWriter writer)
    {
        if (typeParameters.Length == 0)
        {
            return;
        }

        writer.Write("<");
        foreach ((var i, var typeParameter) in typeParameters.IndicesAndItems())
        {
            writer.Write(typeParameter.Name);
            if (i != typeParameters.Length - 1)
            {
                writer.Write(", ");
            }
        }
        writer.Write(">");
    }

    private static void EmitDataClassPropertyProxy(
        IPropertySymbol property,
        INamedTypeSymbol withinType,
        IndentedTextWriter writer,
        Context context)
    {
        EmitAttributes(property, withinType, writer, context, true);
        EmitMainModifiers(property, writer, !property.IsVirtual);
        writer.Write(" ");
        writer.Write(property.Type.ToFullyQualifiedDisplayString());
        writer.Write(" ");
        writer.Write(property.Name);
        writer.WriteLine();

        writer.WriteBracedSectionStart();

        // @todo: if the property (or its setter) is marked private or protected, we need to use UnsafeAccessor

        if (property.GetMethod is not null)
        {
            EmitAttributes(property.GetMethod, withinType, writer, context, false);
            writer.Write("get => ");
            writer.Write(GeneratedInterfaceDataPropertyName);
            writer.Write(".");
            writer.Write(property.Name);
            writer.Write(";");
            writer.WriteLine();
        }

        if (property.SetMethod is not null)
        {
            EmitAttributes(property.SetMethod, withinType, writer, context, false);
            EmitAccessibilityModifiersForPropertyAccessor(property.SetMethod, property, writer);
            writer.Write("set => ");
            writer.Write(GeneratedInterfaceDataPropertyName);
            writer.Write(".");
            writer.Write(property.Name);
            writer.Write(" = value;");
            writer.WriteLine();
        }

        writer.WriteBracedSectionEnd();
    }
}
