using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;
using Franzo.Essentials.Collections;
using Franzo.Essentials.Roslyn;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Franzo.Essentials.InterfaceInheritance.Generator;

public partial class InterfaceInheritanceGenerator : IIncrementalGenerator
{
    internal static void Emit(Context cxt)
    {
        var lk = new object();
        var count = 0;

        Parallel.ForEach(
            cxt.AnalysisData.RootTypesToEmit,
            (type, _, _) =>
            {
                var sb = new StringBuilder();
                var emissionCxt = new TypeEmissionContext(
                    cxt,
                    new IndentedTextWriter(new StringWriter(sb), "    "));

                emissionCxt.Writer.WriteLine("// <auto-generated />");
                emissionCxt.Writer.WriteLine();
                emissionCxt.Writer.WriteLine("#nullable restore annotations");
                emissionCxt.Writer.WriteLine("#nullable disable warnings");
                emissionCxt.Writer.WriteLine("#nullable disable warnings");
                emissionCxt.Writer.WriteLine("#pragma warning disable CS0108");
                emissionCxt.Writer.WriteLine("#pragma warning disable CS0618");
                emissionCxt.Writer.WriteLine("#pragma warning disable CS8387");
                emissionCxt.Writer.WriteLine("#pragma warning disable CS0114");
                emissionCxt.Writer.WriteLine("#pragma warning disable CS0693");
                emissionCxt.Writer.WriteLine();

                EmitTypeWithNamespaceDeclaration(type, emissionCxt);

                var s = sb.ToString();

                lock (lk)
                {
                    cxt.SourceProductionContext.AddSource(
                        $"{type.RoslynSymbol.ToNamespaceQualifiedFileSystemDisplayString()}.cs",
                        s);
                    count++;
                }
            });
    }

    private static void EmitTypeWithNamespaceDeclaration(
        InternalTypeSymbol type,
        TypeEmissionContext cxt)
    {
        if (!type.RoslynSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            cxt.Writer.Write("namespace ");
            cxt.Writer.Write(type.RoslynSymbol.ContainingNamespace.ToDisplayString());
            cxt.Writer.WriteLine();
            cxt.Writer.WriteBracedSectionStart();
        }

        EmitType(type, cxt);

        if (!type.RoslynSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            cxt.Writer.WriteBracedSectionEnd();
        }
    }

    private static void EmitTypes(
        IEnumerable<InternalTypeSymbol> types,
        TypeEmissionContext cxt)
    {
        foreach (var type in types)
        {
            EmitType(type, cxt);
        }
    }

    private static void OpenType(
        InternalTypeSymbol type,
        TypeEmissionContext cxt)
    {
        cxt.Writer.Write("partial");

        if (type.RoslynSymbol.TypeKind is TypeKind.Interface)
        {
            cxt.Writer.Write($" interface");
        }
        else
        {
            if (type.RoslynSymbol.IsRecord)
            {
                cxt.Writer.Write(" record");
            }

            cxt.Writer.Write(" ");
            cxt.Writer.Write(type.RoslynSymbol.TypeKind is TypeKind.Class ? "class" : "struct");
        }

        cxt.Writer.Write(" ");
        cxt.Writer.Write(type.RoslynSymbol.ToSimpleDisplayString());

        if (type.IsDataClass)
        {
            cxt.Writer.Write(" : ");
            cxt.Writer.Write(typeof(InterfaceData).GloballyQualifiedName());
            cxt.Writer.Write("<");
            cxt.Writer.Write(type.ContainingType!.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(">");
        }
        /*else if (type.RoslynSymbol.TypeKind.IsClassOrStruct())
        {
            if (type.AttributeSpecifiedDirectInterfaces.Count > 0)
            {
                cxt.Writer.Write(" : ");
                foreach ((var i, var @interface) in type.AttributeSpecifiedDirectInterfaces.IndicesAndItems())
                {
                    cxt.Writer.Write(@interface.RoslynSymbol.ToFullyQualifiedDisplayString());
                    if (i != type.AttributeSpecifiedDirectInterfaces.Count - 1)
                    {
                        cxt.Writer.Write(", ");
                    }
                }
            }
        }*/

        cxt.Writer.WriteLine();
        cxt.Writer.WriteBracedSectionStart();
    }

    private static void CloseType(TypeEmissionContext cxt)
    {
        cxt.Writer.WriteBracedSectionEnd();
    }

    private static void EmitType(
        InternalTypeSymbol type,
        TypeEmissionContext cxt)
    {
        OpenType(type, cxt);
        cxt.TypeStack.Push(type);

        if (type.IsDataClass)
        {
            cxt.Writer.Write("public static readonly global::System.Reflection.ConstructorInfo ");
            cxt.Writer.Write(GeneratedConstructorPropertyName);
            cxt.Writer.Write(" = typeof(");
            cxt.Writer.Write(type.RoslynSymbol.ToDisplayString());
            cxt.Writer.Write(").GetConstructors()[0];");
            cxt.Writer.WriteLine();

            foreach (var @event in type.DeclaredEvents)
            {
                EmitDataClassEventInvokeMethod(@event, type, cxt);
            }
        }

        if (type.RoslynSymbol.TypeKind.IsClassOrStruct())
        {
            if (!type.IsDataClass)
            {
                EmitRealDataFieldsAndDataPropertyImplementations(type, cxt);
            }

            EmitFakeDataFieldsAndConstructors(type, cxt);
        }

        if (type.DataClass is not null)
        {
            foreach (var property in type.DataClass.DeclaredProperties)
            {
                EmitDataClassPropertyProxy(
                    property.RoslynSymbol,
                    type.RoslynSymbol,
                    cxt);
            }

            foreach (var @event in type.DataClass.DeclaredEvents)
            {
                EmitDataClassEventProxy(
                    @event.RoslynSymbol,
                    type.RoslynSymbol,
                    cxt);
            }

            cxt.Writer.Write("public ");
            cxt.Writer.Write(type.DataClass.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(" ");
            cxt.Writer.Write(GeneratedInterfaceDataPropertyName);
            cxt.Writer.Write(" { get; }");
            cxt.Writer.WriteLine();
        }

        if (type.RoslynSymbol.TypeKind.IsClassOrStruct()
            && !type.DoNotGenerateInheritances)
        {
            foreach (var @interface in type.Interfaces)
            {
                foreach (var feature in @interface.DeclaredFeatures)
                {
                    if (!(feature.RoslynSymbol.IsAccessibleFromType(
                            type.RoslynSymbol,
                            cxt.MainContext.Compilation)
                        || feature.RoslynSymbol.DeclaredAccessibility is Accessibility.Protected
                        || (feature.RoslynSymbol.DeclaredAccessibility is Accessibility.ProtectedAndInternal
                            && feature.RoslynSymbol.ContainingAssembly.GivesAccessTo(
                                    type.RoslynSymbol.ContainingAssembly)))
                        || feature.RoslynSymbol is IMethodSymbol
                        {
                            MethodKind: MethodKind.PropertyGet
                                or MethodKind.PropertySet
                                or MethodKind.EventAdd
                                or MethodKind.EventRemove
                        }
                        || feature.RoslynSymbol is IFieldSymbol
                        {
                            IsConst: false,
                            IsReadOnly: false
                        }
                        || feature.RoslynSymbol.Name == type.RoslynSymbol.Name
                        || (feature.RoslynSymbol.IsVirtual && feature.RoslynSymbol.IsStatic))
                    {
                        continue;
                    }

                    // @todo: once partial properties are in,
                    // we should change this so that we *do* emit inheritances for public abstract properties and methods,
                    // but just mark them them as partial
                    // (ideally we would do so for events too, but it doesn't look like partial events are coming any time soon)
                    // note: above comment is old and probably confusing
                    var featureImpl = type.RoslynSymbol.FindImplementationForInterfaceMember(feature.RoslynSymbol);
                    if (feature.RoslynSymbol.DeclaredAccessibility is Accessibility.Public
                        && feature.RoslynSymbol.IsAbstract
                        && type.DirectInterfaces.All(
                            i => i.RoslynSymbol.FindImplementationForInterfaceMember(feature.RoslynSymbol) is null)
                        && (featureImpl is null || !featureImpl.IsExplicitImplementationFor(feature.RoslynSymbol)))
                    {
                        continue;
                    }

                    // @perf: checking directinterfaces is redundant here
                    // now that classes specify their interface lists before generation
                    // other places probably have similar redundancies too
                    if (feature.TypesDeclaringShadowingFeatures.Any(
                        shadowingType => type.RoslynSymbol.IsAssignableTo(
                                shadowingType.RoslynSymbol,
                                cxt.MainContext.Compilation)
                            || type.DirectInterfaces.Any(
                                i => i.RoslynSymbol.IsAssignableTo(
                                    shadowingType.RoslynSymbol,
                                    cxt.MainContext.Compilation))))
                    {
                        continue;
                    }

                    EmitFeatureInheritance(
                        feature,
                        @interface.RoslynSymbol,
                        type.RoslynSymbol,
                        cxt);
                }
            }
        }

        foreach (var @interface in type.DirectInterfaces)
        {
            EmitAsInterfaceMethod(@interface, cxt);
        }

        if (type.EmitDefaultConstructor)
        {
            cxt.Writer.Write("public ");
            cxt.Writer.Write(type.RoslynSymbol.Name);
            cxt.Writer.Write("()");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionStart();

            foreach (var @interface in type.AnchorType.DirectInterfaces)
            {
                if (@interface.DataClass is null) continue;

                EmitFakeDataFieldName(@interface, cxt);
                cxt.Writer.Write(" = ");
                EmitConstructMethodName(@interface, cxt);
                cxt.Writer.Write("();");
                cxt.Writer.WriteLine();
            }

            cxt.Writer.WriteBracedSectionEnd();
        }

        foreach (var memberType in type.DeclaredTypes)
        {
            EmitType(memberType, cxt);
        }

        CloseType(cxt);
        cxt.TypeStack.Pop();
    }

    private static void EmitDataClassEventInvokeMethod(
        InternalEventSymbol @event,
        InternalTypeSymbol type,
        TypeEmissionContext cxt)
    {
        EmitEventInvokeMethod(
            @event.RoslynSymbol,
            type.RoslynSymbol,
            cxt,
            isProxy: false);
    }

    private static void EmitRealDataFieldsAndDataPropertyImplementations(
        InternalTypeSymbol type,
        TypeEmissionContext cxt)
    {
        foreach (var @interface in type.Interfaces)
        {
            if (@interface.DataClass is null) continue;

            cxt.Writer.Write("private ");
            cxt.Writer.Write(@interface.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(".");
            cxt.Writer.Write(InterfaceDataClassName);
            cxt.Writer.Write(" ");
            EmitRealDataFieldName(@interface, cxt);
            cxt.Writer.WriteLine();

            cxt.Writer.Indent++;
            cxt.Writer.Write("= (");
            cxt.Writer.Write(@interface.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(".");
            cxt.Writer.Write(InterfaceDataClassName);
            cxt.Writer.Write(")global::System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(typeof(");
            cxt.Writer.Write(@interface.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(".");
            cxt.Writer.Write(InterfaceDataClassName);
            cxt.Writer.Write("));");
            cxt.Writer.WriteLine();
            cxt.Writer.Indent--;
        }

        foreach (var @interface in type.Interfaces)
        {
            if (@interface.DataClass is null) continue;

            cxt.Writer.Write(@interface.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(".");
            cxt.Writer.Write(InterfaceDataClassName);
            cxt.Writer.Write(" ");
            cxt.Writer.Write(@interface.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(".");
            cxt.Writer.Write(GeneratedInterfaceDataPropertyName);
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionStart();
            cxt.Writer.Write("get => ");
            EmitRealDataFieldName(@interface, cxt);
            cxt.Writer.Write(";");
            cxt.Writer.WriteLine();
            cxt.Writer.WriteBracedSectionEnd();
        }
    }

    private static void EmitAsInterfaceMethod(
        InternalTypeSymbol @interface,
        TypeEmissionContext cxt)
    {
        cxt.Writer.Write("private ");
        cxt.Writer.Write(@interface.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" As");
        cxt.Writer.Write(@interface.RoslynSymbol.MemberifiedName());
        cxt.Writer.Write("()");
        cxt.Writer.WriteLine();
        cxt.Writer.WriteBracedSectionStart();
        cxt.Writer.WriteLine("return this;");
        cxt.Writer.WriteBracedSectionEnd();
    }

    private static void EmitFakeDataFieldsAndConstructors(
        InternalTypeSymbol type,
        TypeEmissionContext cxt)
    {
        foreach (var @interface in type.AnchorType.DirectInterfaces)
        {
            if (@interface.DataClass is null) continue;

            cxt.Writer.Write("private ");
            cxt.Writer.Write(@interface.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(".");
            cxt.Writer.Write(InterfaceDataClassName);
            cxt.Writer.Write(" ");
            EmitFakeDataFieldName(@interface, cxt);
            cxt.Writer.Write(";");
            cxt.Writer.WriteLine();
        }

        foreach (var @interface in type.AnchorType.DirectInterfaces)
        {
            if (@interface.DataClass is null) continue;

            cxt.Writer.Write("private ");
            cxt.Writer.Write(@interface.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(".");
            cxt.Writer.Write(InterfaceDataClassName);
            cxt.Writer.Write(" ");
            EmitConstructMethodName(@interface, cxt);
            EmitMethodParameterList(
                @interface.DataClass.ConstructorIfDataClass!.RoslynSymbol,
                type.RoslynSymbol,
                cxt);
            cxt.Writer.WriteLine();
            cxt.Writer.WriteBracedSectionStart();

            cxt.Writer.Write("if (");
            if (type.IsDataClass)
            {
                cxt.Writer.Write("((");
                cxt.Writer.Write(@interface.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
                cxt.Writer.Write(")");
                cxt.Writer.Write(nameof(InterfaceData<object>.This));
                cxt.Writer.Write(").");
                cxt.Writer.Write(GeneratedInterfaceDataPropertyName);
            }
            else
            {
                EmitRealDataFieldName(@interface, cxt);
            }
            cxt.Writer.Write(".");
            cxt.Writer.Write(nameof(InterfaceData.__IsConstructed));
            cxt.Writer.Write(") return null!;");
            cxt.Writer.WriteLine();

            if (!type.IsDataClass)
            {
                foreach (var ancestorInterface in @interface.SelfAndInterfaces)
                {
                    if (ancestorInterface.DataClass is null) continue;

                    EmitRealDataFieldName(ancestorInterface, cxt);
                    cxt.Writer.Write(".");
                    cxt.Writer.Write(nameof(InterfaceData<object>.__This));
                    cxt.Writer.Write(" = this;");
                    cxt.Writer.WriteLine();
                }
            }

            // @todo: remove string interpolations if needed for perf

            // @todo: create delegate and invoke that instead
            cxt.Writer.Write(@interface.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(".");
            cxt.Writer.Write(InterfaceDataClassName);
            cxt.Writer.Write(".");
            cxt.Writer.Write(GeneratedConstructorPropertyName);
            cxt.Writer.Write(".Invoke(");
            if (type.IsDataClass)
            {
                cxt.Writer.Write("((");
                cxt.Writer.Write(@interface.RoslynSymbol.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
                cxt.Writer.Write(")");
                cxt.Writer.Write(nameof(InterfaceData<object>.This));
                cxt.Writer.Write(").");
                cxt.Writer.Write(GeneratedInterfaceDataPropertyName);
            }
            else
            {
                EmitRealDataFieldName(@interface, cxt);
            }
            cxt.Writer.Write(", new object?[] { ");
            EmitUnparenthesizedArgumentListFromParameters(
                @interface.DataClass.ConstructorIfDataClass.RoslynSymbol.Parameters,
                cxt);
            cxt.Writer.Write(" });");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteLine($"return null!;");

            cxt.Writer.WriteBracedSectionEnd();
        }
    }

    private static void EmitFakeDataFieldName(
        InternalTypeSymbol @interface,
        TypeEmissionContext cxt)
    {
        cxt.Writer.Write(@interface.RoslynSymbol.MemberifiedName());
        cxt.Writer.Write("Data");
    }

    private static void EmitConstructMethodName(
        InternalTypeSymbol @interface,
        TypeEmissionContext cxt)
    {
        cxt.Writer.Write("Construct");
        cxt.Writer.Write(@interface.RoslynSymbol.MemberifiedName());
    }

    private static void EmitRealDataFieldName(
        InternalTypeSymbol @interface,
        TypeEmissionContext cxt)
    {
        cxt.Writer.Write("__");
        EmitFakeDataFieldName(@interface, cxt);
    }

    private static void EmitMainModifiers(
        ISymbol symbol,
        TypeEmissionContext cxt,
        bool includeSealed = false)
    {
        EmitAccessibilityModifiers(symbol.DeclaredAccessibility, cxt);

        if (includeSealed)
        {
            cxt.Writer.Write(" sealed");
        }

        if (symbol.IsStatic && symbol is not IFieldSymbol { IsConst: true })
        {
            cxt.Writer.Write(" static");
        }
    }

    private static void EmitAccessibilityModifiers(
        Accessibility accessibility,
        TypeEmissionContext cxt)
    {
        if (accessibility is Accessibility.Public)
        {
            cxt.Writer.Write("public");
        }
        else if (accessibility is Accessibility.Protected)
        {
            cxt.Writer.Write("protected");
        }
        else if (accessibility is Accessibility.Internal)
        {
            cxt.Writer.Write("internal");
        }
        else if (accessibility is Accessibility.Private)
        {
            cxt.Writer.Write("private");
        }
        else if (accessibility is Accessibility.ProtectedOrInternal)
        {
            cxt.Writer.Write("protected internal");
        }
        else if (accessibility is Accessibility.ProtectedAndInternal)
        {
            cxt.Writer.Write("private protected");
        }
    }

    private static void EmitAttributes(
        ISymbol symbol,
        INamedTypeSymbol withinType,
        TypeEmissionContext cxt,
        bool separateLines)
    {
        var attributes = symbol.GetAttributes();
        // Note: protected/private protected member types in a interface CAN currently be accessed by implementing classes
        foreach ((var attribute, var last) in attributes.WithLastFlag())
        {
            if (attribute.AttributeClass is null
                || attribute.AttributeClass.IsCompilerGeneratedAttributeType()
                || !attribute.AttributeClass.IsAccessibleFromType(
                    withinType,
                    cxt.MainContext.Compilation)
                || attribute.AttributeClass.TypeArguments.Any(
                    a => !a.IsAccessibleFromType(withinType, cxt.MainContext.Compilation))
                || attribute.ConstructorArguments
                    .Concat(attribute.NamedArguments.Select(p => p.Value))
                    .Any(arg => arg.Kind is TypedConstantKind.Error)
                || attribute.AttributeConstructor is null
                || !attribute.AttributeConstructor.IsAccessibleFromType(
                    withinType,
                    cxt.MainContext.Compilation))
            {
                continue;
            }

            EmitAttribute(attribute, cxt);

            if (separateLines)
            {
                cxt.Writer.WriteLine();
            }
            else
            {
                if (!last)
                {
                    cxt.Writer.Write(" ");
                }
            }
        }
    }

    private static void EmitAttribute(AttributeData attribute, TypeEmissionContext cxt)
    {
        cxt.Writer.Write("[");
        cxt.Writer.Write(attribute.AttributeClass!.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write("(");

        foreach ((var argument, var last) in attribute.ConstructorArguments.WithLastFlag())
        {
            EmitTypedConstant(argument, cxt);
            if (!last || attribute.NamedArguments.Length > 0)
            {
                cxt.Writer.Write(", ");
            }
        }

        foreach ((var pair, var last) in attribute.NamedArguments.WithLastFlag())
        {
            cxt.Writer.Write(pair.Key);
            cxt.Writer.Write(" = ");
            EmitTypedConstant(pair.Value, cxt);
            if (!last)
            {
                cxt.Writer.Write(", ");
            }
        }

        cxt.Writer.Write(")]");
    }

    private static void EmitTypedConstant(TypedConstant typedConstant, TypeEmissionContext cxt)
    {
        Debug.Assert(typedConstant.Kind is not TypedConstantKind.Error && typedConstant.Type is not null);

        if (typedConstant.IsNull)
        {
            EmitNull(cxt);
        }
        else
        {
            switch (typedConstant.Kind)
            {
                case TypedConstantKind.Array:
                    EmitArrayTypedConstant(typedConstant, cxt);
                    break;
                case TypedConstantKind.Primitive or TypedConstantKind.Enum:
                    EmitConstant(typedConstant.Value, typedConstant.Type!, cxt);
                    break;
                case TypedConstantKind.Type:
                    EmitTypeTypedConstant(typedConstant, cxt);
                    break;
            };
        }
    }

    private static void EmitArrayTypedConstant(TypedConstant self, TypeEmissionContext cxt)
    {
        Debug.Assert(self.Type is not null);

        var arrayType = (IArrayTypeSymbol)self.Type!;
        cxt.Writer.Write("new ");
        cxt.Writer.Write(arrayType.ElementType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write("[] { ");
        EmitCommaSeparatedTypedConstants(self.Values, cxt);
        cxt.Writer.Write(" }");
    }

    private static void EmitCommaSeparatedTypedConstants(
        ImmutableArray<TypedConstant> typedConstants,
        TypeEmissionContext cxt)
    {
        foreach ((var typedConstant, var last) in typedConstants.WithLastFlag())
        {
            EmitTypedConstant(typedConstant, cxt);
            if (!last)
            {
                cxt.Writer.Write(", ");
            }
        }
    }

    private static void EmitConstant(
        object? constant,
        ITypeSymbol constantType,
        TypeEmissionContext cxt)
    {
        if (constant is null)
        {
            EmitNull(cxt);
        }
        else if (constantType.TypeKind is TypeKind.Enum)
        {
            EmitEnumValueFromConstant(constant, (INamedTypeSymbol)constantType, cxt);
        }
        else if (constant is char c)
        {
            cxt.Writer.Write("'");
            cxt.Writer.Write(c);
            cxt.Writer.Write("'");
        }
        else if (constant is string str)
        {
            cxt.Writer.Write(SyntaxFactory.Literal(str).ToString());
        }
        else if (constant is bool b)
        {
            cxt.Writer.Write(b ? "true" : "false");
        }
        else
        {
            cxt.Writer.Write(constant);
        }
    }

    private static void EmitEnumValueFromConstant(
        object constant,
        INamedTypeSymbol enumType,
        TypeEmissionContext cxt)
    {
        IFieldSymbol matchingField = null!;
        foreach (var member in enumType.GetMembers())
        {
            var field = (IFieldSymbol)member;
            if (object.Equals(field.ConstantValue, constant))
            {
                matchingField = field;
                break;
            }
        }

        cxt.Writer.Write(enumType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(".");
        cxt.Writer.Write(matchingField.Name);
    }

    private static void EmitTypeTypedConstant(
        TypedConstant typedConstant,
        TypeEmissionContext cxt)
    {
        var type = (INamedTypeSymbol)typedConstant.Value!;
        cxt.Writer.Write("typeof(");
        cxt.Writer.Write(type.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(")");
    }

    private static void EmitNull(TypeEmissionContext cxt)
    {
        cxt.Writer.Write("null");
    }

    private static void EmitMethodParameterList(
        IMethodSymbol method,
        INamedTypeSymbol withinType,
        TypeEmissionContext cxt,
        bool isForUnsafeAccessor = false)
    {
        cxt.Writer.Write("(");
        EmitUnparenthesizedParameterList(
            method.Parameters,
            withinType,
            cxt,
            isForUnsafeAccessor);
        cxt.Writer.Write(")");
    }

    private static void EmitUnparenthesizedParameterList(
        ImmutableArray<IParameterSymbol> parameters,
        INamedTypeSymbol withinType,
        TypeEmissionContext cxt,
        bool isForUnsafeAccessor = false)
    {
        foreach (((var i, var parameter), var last) in parameters.IndicesAndItems().WithLastFlag())
        {
            if (!isForUnsafeAccessor)
            {
                EmitAttributes(parameter, withinType, cxt, false);
            }

            var refKindModifier = parameter.RefKind.ToCSharpString();
            if (refKindModifier is not null)
            {
                cxt.Writer.Write(refKindModifier);
                cxt.Writer.Write(" ");
            }

            cxt.Writer.Write(parameter.Type.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(" ");

            if (isForUnsafeAccessor)
            {
                cxt.Writer.Write("a");
                cxt.Writer.Write(i);
            }
            else
            {
                parameter.WriteVerbatimizedName(cxt.Writer);
            }

            if (parameter.HasExplicitDefaultValue && !isForUnsafeAccessor)
            {
                cxt.Writer.Write(" = ");
                EmitConstant(parameter.ExplicitDefaultValue, parameter.Type, cxt);
            }

            if (!last)
            {
                cxt.Writer.Write(", ");
            }
        }
    }

    /*private static void EmitUnparenthesizedArgumentListFromMethodParameters(
        IMethodSymbol method,
        TypeEmissionContext cxt,
        bool isForUnsafeAccessor = false)
    {
        EmitUnparenthesizedArgumentListFromParameters(
            method.Parameters,
            writer,
            isForUnsafeAccessor);
    }*/

    private static void EmitUnparenthesizedArgumentListFromParameters(
        ImmutableArray<IParameterSymbol> parameters,
        TypeEmissionContext cxt)
    {
        foreach ((var parameter, var last) in parameters.WithLastFlag())
        {
            var refKindModifier = parameter.RefKind.ToCSharpString();
            if (refKindModifier is not null)
            {
                cxt.Writer.Write(refKindModifier);
                cxt.Writer.Write(" ");
            }

            parameter.WriteVerbatimizedName(cxt.Writer);

            if (!last)
            {
                cxt.Writer.Write(", ");
            }
        }
    }

    private static void EmitFeatureInheritance(
        InternalFeatureSymbol feature,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        TypeEmissionContext cxt)
    {
        EmitAttributes(feature.RoslynSymbol, withinType, cxt, true);
        if (feature is not InternalFieldSymbol
            && feature.RoslynSymbol.DeclaredAccessibility is Accessibility.Public
            && !feature.HasOverrideAttribute)
        {
            cxt.Writer.Write("[");
#pragma warning disable CS0618
            cxt.Writer.Write(typeof(InterfaceInheritanceDevirtualizeAttribute).GloballyQualifiedName());
#pragma warning restore CS0618
            cxt.Writer.Write("]");
            cxt.Writer.WriteLine();
        }
        EmitMainModifiers(feature.RoslynSymbol, cxt);
        if (feature.HasOverrideAttribute)
        {
            cxt.Writer.Write(" override");
        }

        cxt.Writer.Write(" ");

        switch (feature)
        {
            case InternalPropertySymbol property:
                EmitPropertyInheritanceCore(property, declaringType, withinType, cxt);
                break;
            case InternalFieldSymbol field:
                EmitFieldInheritanceCore(field, declaringType, withinType, cxt);
                break;
            case InternalEventSymbol @event:
                EmitEventInheritanceCore(@event, declaringType, withinType, cxt);
                break;
            case InternalMethodSymbol method:
                EmitMethodInheritanceCore(method, declaringType, withinType, cxt);
                break;
        }
    }

    private static void EmitFeatureLocationExpression(
        InternalFeatureSymbol feature,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt)
    {
        if (feature.RoslynSymbol.IsStatic)
        {
            cxt.Writer.Write(declaringType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        }
        else
        {
            cxt.Writer.Write("((");
            cxt.Writer.Write(declaringType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(")this)");
        }
    }

    private static void EmitPropertyInheritanceCore(
        InternalPropertySymbol property,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        TypeEmissionContext cxt)
    {
        cxt.Writer.Write(property.RoslynSymbol.Type.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" ");
        if (property.RoslynSymbol.IsIndexer)
        {
            cxt.Writer.Write("this[");
            EmitUnparenthesizedParameterList(
                property.RoslynSymbol.Parameters,
                withinType,
                cxt);
            cxt.Writer.Write("]");
        }
        else
        {
            cxt.Writer.Write(property.RoslynSymbol.Name);
        }
        cxt.Writer.WriteLine();

        cxt.Writer.WriteBracedSectionStart();

        if (property.RoslynSymbol.GetMethod is not null)
        {
            EmitAttributes(property.RoslynSymbol.GetMethod, withinType, cxt, false);
            cxt.Writer.Write("get");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionStart();

            if (property.RoslynSymbol.IsProtectedOrProtectedAndOrInternal()
                && !property.RoslynSymbol.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
            {
                EmitUnsafeGetterAccessorForProperty(property.RoslynSymbol, declaringType, cxt);
            }

            cxt.Writer.Write("return ");

            if (property.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
            {
                if (property.RoslynSymbol.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
                {
                    EmitUnsafeAccessorClassQualification(
                        property.RoslynSymbol.GetMethod,
                        declaringType,
                        cxt);
                }

                EmitUnsafeGetterInvocationForProperty(property.RoslynSymbol, cxt, "this");
            }
            else
            {
                EmitAccessExpressionForPropertyInheritance(property, declaringType, cxt);
            }

            cxt.Writer.Write(";");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionEnd();
        }

        if (property.RoslynSymbol.SetMethod is not null
            && property.RoslynSymbol.SetMethod.DeclaredAccessibility is not Accessibility.Private)
        {
            EmitAttributes(property.RoslynSymbol.SetMethod, withinType, cxt, false);
            EmitAccessibilityModifiersForPropertyAccessor(
                property.RoslynSymbol.SetMethod,
                property.RoslynSymbol,
                cxt);
            cxt.Writer.Write("set");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionStart();

            if (property.RoslynSymbol.SetMethod.IsProtectedOrProtectedAndOrInternal())
            {
                if (property.RoslynSymbol.SetMethod.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
                {
                    EmitUnsafeAccessorClassQualification(
                        property.RoslynSymbol.SetMethod,
                        declaringType,
                        cxt);
                }
                else
                {
                    EmitUnsafeSetterAccessorForProperty(property.RoslynSymbol, declaringType, cxt);
                }

                EmitUnsafeSetterInvocationForProperty(property.RoslynSymbol, cxt, "this");
            }
            else
            {
                EmitAccessExpressionForPropertyInheritance(property, declaringType, cxt);
                cxt.Writer.Write(" = value");
            }

            cxt.Writer.Write(";");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionEnd();
        }

        cxt.Writer.WriteBracedSectionEnd();

        if (property.RoslynSymbol.GetMethod is not null
            && property.RoslynSymbol.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
        {
            EmitUnsafeGetterAccessorClassForProperty(property.RoslynSymbol, declaringType, cxt);
        }

        if (property.RoslynSymbol.SetMethod is not null
            && property.RoslynSymbol.SetMethod.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
        {
            EmitUnsafeSetterAccessorClassForProperty(property.RoslynSymbol, declaringType, cxt);
        }
    }

    private static void EmitAccessExpressionForPropertyInheritance(
        InternalPropertySymbol property,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt)
    {
        EmitFeatureLocationExpression(property, declaringType, cxt);

        if (property.RoslynSymbol.IsIndexer)
        {
            cxt.Writer.Write("[");
            EmitUnparenthesizedArgumentListFromParameters(property.RoslynSymbol.Parameters, cxt);
            cxt.Writer.Write("]");
        }
        else
        {
            cxt.Writer.Write(".");
            cxt.Writer.Write(property.RoslynSymbol.Name);
        }
    }

    private static void EmitAccessibilityModifiersForPropertyAccessor(
        IMethodSymbol accessor,
        IPropertySymbol property,
        TypeEmissionContext cxt)
    {
        if (accessor.DeclaredAccessibility == property.DeclaredAccessibility)
        {
            return;
        }

        if (accessor.DeclaredAccessibility is Accessibility.Protected)
        {
            cxt.Writer.Write("protected");
        }
        else if (accessor.DeclaredAccessibility is Accessibility.Internal)
        {
            cxt.Writer.Write("internal");
        }
        else if (accessor.DeclaredAccessibility is Accessibility.Private)
        {
            cxt.Writer.Write("private");
        }
        else if (accessor.DeclaredAccessibility is Accessibility.ProtectedOrInternal)
        {
            cxt.Writer.Write("protected internal");
        }
        else if (accessor.DeclaredAccessibility is Accessibility.ProtectedAndInternal)
        {
            cxt.Writer.Write("private protected");
        }

        cxt.Writer.Write(" ");
    }

    private static void EmitFieldInheritanceCore(
        InternalFieldSymbol field,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        TypeEmissionContext cxt)
    {
        if (field.RoslynSymbol.IsReadOnly)
        {
            cxt.Writer.Write("readonly ");
        }
        else if (field.RoslynSymbol.IsConst)
        {
            cxt.Writer.Write("const ");
        }
        cxt.Writer.Write(field.RoslynSymbol.Type.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" ");
        cxt.Writer.Write(field.RoslynSymbol.Name);
        cxt.Writer.Write(" = ");

        if (field.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
        {
            if (field.RoslynSymbol.IsConst)
            {
                EmitConstant(field.RoslynSymbol.ConstantValue, field.RoslynSymbol.Type, cxt);
            }
            else
            {
                if (field.RoslynSymbol.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
                {
                    EmitUnsafeAccessorClassQualification(field.RoslynSymbol, declaringType, cxt);
                }

                field.RoslynSymbol.WriteUnsafeAccessorName(cxt.Writer);
                cxt.Writer.Write("(null!)");
            }
        }
        else
        {
            EmitFeatureLocationExpression(field, declaringType, cxt);
            cxt.Writer.Write(".");
            cxt.Writer.Write(field.RoslynSymbol.Name);
        }

        cxt.Writer.Write(";");
        cxt.Writer.WriteLine();

        if (field.RoslynSymbol.IsProtectedOrProtectedAndOrInternal() && !field.RoslynSymbol.IsConst)
        {
            if (field.RoslynSymbol.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
            {
                EmitUnsafeAccessorClassForField(field.RoslynSymbol, declaringType, cxt);
            }
            else
            {
                EmitUnsafeAccessorForField(field.RoslynSymbol, declaringType, cxt);
            }
        }
    }

    private static void EmitEventInheritanceCore(
        InternalEventSymbol @event,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        TypeEmissionContext cxt)
    {
        cxt.Writer.Write("event ");
        cxt.Writer.Write(@event.RoslynSymbol.Type.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" ");
        cxt.Writer.Write(@event.RoslynSymbol.Name);
        cxt.Writer.WriteLine();

        cxt.Writer.WriteBracedSectionStart();

        if (@event.RoslynSymbol.AddMethod is not null)
        {
            EmitAttributes(@event.RoslynSymbol.AddMethod, withinType, cxt, false);
            cxt.Writer.Write("add");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionStart();

            if (@event.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
            {
                if (@event.RoslynSymbol.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
                {
                    EmitUnsafeAccessorClassQualification(
                        @event.RoslynSymbol.AddMethod,
                        declaringType,
                        cxt);
                }
                else
                {
                    EmitUnsafeAddMethodAccessorForEvent(@event.RoslynSymbol, declaringType, cxt);
                }

                EmitUnsafeAddMethodInvocationForEvent(@event.RoslynSymbol, cxt, "this");
            }
            else
            {
                EmitFeatureLocationExpression(@event, declaringType, cxt);
                cxt.Writer.Write(".");
                cxt.Writer.Write(@event.RoslynSymbol.Name);
                cxt.Writer.Write(" += value");
            }

            cxt.Writer.Write(";");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionEnd();
        }

        if (@event.RoslynSymbol.RemoveMethod is not null)
        {
            EmitAttributes(@event.RoslynSymbol.RemoveMethod, withinType, cxt, false);
            cxt.Writer.Write("remove");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionStart();

            if (@event.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
            {
                if (@event.RoslynSymbol.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
                {
                    EmitUnsafeAccessorClassQualification(
                        @event.RoslynSymbol.RemoveMethod,
                        declaringType,
                        cxt);
                }
                else
                {
                    EmitUnsafeRemoveMethodAccessorForEvent(@event.RoslynSymbol, declaringType, cxt);
                }

                EmitUnsafeRemoveMethodInvocationForEvent(@event.RoslynSymbol, cxt, "this");
            }
            else
            {
                EmitFeatureLocationExpression(@event, declaringType, cxt);
                cxt.Writer.Write(".");
                cxt.Writer.Write(@event.RoslynSymbol.Name);
                cxt.Writer.Write(" -= value");
            }

            cxt.Writer.Write(";");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionEnd();
        }

        cxt.Writer.WriteBracedSectionEnd();

        if (@event.RoslynSymbol.AddMethod is not null
            && @event.RoslynSymbol.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
        {
            EmitUnsafeAddMethodAccessorClassForEvent(@event.RoslynSymbol, declaringType, cxt);
        }

        if (@event.RoslynSymbol.RemoveMethod is not null
            && @event.RoslynSymbol.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
        {
            EmitUnsafeRemoveMethodAccessorClassForEvent(@event.RoslynSymbol, declaringType, cxt);
        }
    }

    private static void EmitMethodInheritanceCore(
        InternalMethodSymbol method,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        TypeEmissionContext cxt)
    {
        EmitMethodCoreSignature(method.RoslynSymbol, declaringType, withinType, cxt);
        cxt.Writer.WriteLine();

        cxt.Writer.WriteBracedSectionStart();

        if (method.RoslynSymbol.IsProtectedOrProtectedAndOrInternal()
            && !method.RoslynSymbol.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
        {
            EmitUnsafeAccessorForMethod(method.RoslynSymbol, declaringType, cxt);
        }

        if (!method.RoslynSymbol.ReturnsVoid)
        {
            cxt.Writer.Write("return ");
        }

        if (method.RoslynSymbol.IsProtectedOrProtectedAndOrInternal())
        {
            if (method.RoslynSymbol.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
            {
                EmitUnsafeAccessorClassQualification(method.RoslynSymbol, declaringType, cxt);
            }

            cxt.Writer.Write(method.RoslynSymbol.Name);
            //method.RoslynSymbol.WriteUnsafeAccessorName(writer);
            EmitTypeParameterList(method.RoslynSymbol.TypeParameters, cxt);
            cxt.Writer.Write("(");
            if (method.RoslynSymbol.IsStatic)
            {
                cxt.Writer.Write("null!");
            }
            else
            {
                cxt.Writer.Write("this");
            }

            if (method.RoslynSymbol.Parameters.Length > 0)
            {
                cxt.Writer.Write(", ");
                EmitUnparenthesizedArgumentListFromParameters(method.RoslynSymbol.Parameters, cxt);
            }
            cxt.Writer.Write(")");
        }
        else
        {
            EmitFeatureLocationExpression(method, declaringType, cxt);
            cxt.Writer.Write(".");
            cxt.Writer.Write(method.RoslynSymbol.Name);
            EmitTypeParameterList(method.RoslynSymbol.TypeParameters, cxt);
            cxt.Writer.Write("(");
            EmitUnparenthesizedArgumentListFromParameters(method.RoslynSymbol.Parameters, cxt);
            cxt.Writer.Write(")");
        }

        cxt.Writer.Write(";");
        cxt.Writer.WriteLine();

        cxt.Writer.WriteBracedSectionEnd();

        if (method.RoslynSymbol.IsProtectedOrProtectedAndOrInternalAndOriginalDefinitionIsGenericTypeContained())
        {
            EmitUnsafeAccessorClassForMethod(method.RoslynSymbol, declaringType, cxt);
        }
    }

    private static void EmitMethodCoreSignature(
        IMethodSymbol method,
        INamedTypeSymbol declaringType,
        INamedTypeSymbol withinType,
        TypeEmissionContext cxt,
        bool isForUnsafeAccessor = false)
    {
        cxt.Writer.Write(method.ReturnType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" ");
        /*if (isForUnsafeAccessor)
        {
            method.WriteUnsafeAccessorName(writer);
        }
        else
        {*/
        cxt.Writer.Write(method.Name);
        //}
        EmitTypeParameterList(method.TypeParameters, cxt);
        cxt.Writer.Write("(");
        if (isForUnsafeAccessor)
        {
            cxt.Writer.Write(declaringType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(" c");
            if (method.Parameters.Length > 0)
            {
                cxt.Writer.Write(", ");
            }
        }
        EmitUnparenthesizedParameterList(
            method.Parameters,
            withinType,
            cxt,
            isForUnsafeAccessor: isForUnsafeAccessor);
        cxt.Writer.Write(")");
        EmitConstraintClausesWithLeadingNewLineIfAny(method.TypeParameters, cxt);
    }

    private static void EmitConstraintClausesWithLeadingNewLineIfAny(
        ImmutableArray<ITypeParameterSymbol> typeParameters,
        TypeEmissionContext cxt)
    {
        foreach (var typeParameter in typeParameters)
        {
            if (!typeParameter.HasConstraints()) continue;

            cxt.Writer.WriteLine();

            // @todo: EnumerableExtensions.WithLastFlag

            cxt.Writer.Indent++;

            cxt.Writer.Write("where ");
            cxt.Writer.Write(typeParameter.Name);
            cxt.Writer.Write(" : ");

            var constraintStrings = EnumerateConstraintStrings(typeParameter).ToArray();
            foreach ((var constraintString, var last) in constraintStrings.WithLastFlag())
            {
                cxt.Writer.Write(constraintString);
                if (!last)
                {
                    cxt.Writer.Write(", ");
                }
            }

            cxt.Writer.Indent--;
        }
    }

    private static IEnumerable<string> EnumerateConstraintStrings(
        ITypeParameterSymbol typeParameter)
    {
        if (typeParameter.HasReferenceTypeConstraint)
        {
            if (typeParameter.ReferenceTypeConstraintNullableAnnotation is NullableAnnotation.Annotated)
            {
                yield return "class?";
            }
            else
            {
                yield return "class";
            }
        }

        if (typeParameter.HasValueTypeConstraint && !typeParameter.HasUnmanagedTypeConstraint)
        {
            yield return "struct";
        }

        if (typeParameter.HasUnmanagedTypeConstraint)
        {
            yield return "unmanaged";
        }

        if (typeParameter.HasNotNullConstraint)
        {
            yield return "notnull";
        }

        foreach (var constraintType in typeParameter.ConstraintTypes)
        {
            yield return constraintType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString();
        }

        if (typeParameter.HasConstructorConstraint)
        {
            yield return "new()";
        }
    }

    private static void EmitTypeParameterList(
        ImmutableArray<ITypeParameterSymbol> typeParameters,
        TypeEmissionContext cxt)
    {
        if (typeParameters.Length == 0)
        {
            return;
        }

        cxt.Writer.Write("<");
        foreach ((var typeParameter, var last) in typeParameters.WithLastFlag())
        {
            cxt.Writer.Write(typeParameter.Name);
            if (!last)
            {
                cxt.Writer.Write(", ");
            }
        }
        cxt.Writer.Write(">");
    }

    private static void EmitDataClassPropertyProxy(
        IPropertySymbol property,
        INamedTypeSymbol withinType,
        TypeEmissionContext cxt)
    {
        EmitAttributes(property, withinType, cxt, true);
        EmitMainModifiers(
            property,
            cxt,
            includeSealed: !property.IsVirtual && property.DeclaredAccessibility is not Accessibility.Private);
        cxt.Writer.Write(" ");
        cxt.Writer.Write(property.Type.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" ");
        cxt.Writer.Write(property.Name);
        cxt.Writer.WriteLine();

        cxt.Writer.WriteBracedSectionStart();

        if (property.GetMethod is not null)
        {
            EmitAttributes(property.GetMethod, withinType, cxt, false);
            cxt.Writer.Write("get");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionStart();

            if (!property.IsPublicOrInternal())
            {
                EmitUnsafeGetterAccessorForProperty(property, property.ContainingType, cxt);
            }

            cxt.Writer.Write("return ");
            if (property.IsPublicOrInternal())
            {
                cxt.Writer.Write(GeneratedInterfaceDataPropertyName);
                cxt.Writer.Write(".");
                cxt.Writer.Write(property.Name);
            }
            else
            {
                EmitUnsafeGetterInvocationForProperty(
                    property,
                    cxt,
                    GeneratedInterfaceDataPropertyName);
            }

            cxt.Writer.Write(";");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionEnd();
        }

        if (property.SetMethod is not null)
        {
            EmitAttributes(property.SetMethod, withinType, cxt, false);
            EmitAccessibilityModifiersForPropertyAccessor(property.SetMethod, property, cxt);
            cxt.Writer.Write("set");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionStart();

            if (property.SetMethod.IsPublicOrInternal())
            {
                cxt.Writer.Write(GeneratedInterfaceDataPropertyName);
                cxt.Writer.Write(".");
                cxt.Writer.Write(property.Name);
                cxt.Writer.Write(" = value");
            }
            else
            {
                EmitUnsafeSetterAccessorForProperty(property, property.ContainingType, cxt);
                EmitUnsafeSetterInvocationForProperty(
                    property,
                    cxt,
                    GeneratedInterfaceDataPropertyName);
            }

            cxt.Writer.Write(";");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionEnd();
        }

        cxt.Writer.WriteBracedSectionEnd();
    }

    private static void EmitDataClassEventProxy(
        IEventSymbol @event,
        INamedTypeSymbol withinType,
        TypeEmissionContext cxt)
    {
        EmitAttributes(@event, withinType, cxt, true);
        EmitMainModifiers(
            @event,
            cxt,
            includeSealed: !@event.IsVirtual && @event.DeclaredAccessibility is not Accessibility.Private);
        cxt.Writer.Write(" event ");
        cxt.Writer.Write(@event.Type.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" ");
        cxt.Writer.Write(@event.Name);
        cxt.Writer.WriteLine();

        cxt.Writer.WriteBracedSectionStart();

        if (@event.AddMethod is not null)
        {
            EmitAttributes(@event.AddMethod, withinType, cxt, false);
            cxt.Writer.Write("add");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionStart();

            if (@event.IsPublicOrInternal())
            {
                cxt.Writer.Write(GeneratedInterfaceDataPropertyName);
                cxt.Writer.Write(".");
                cxt.Writer.Write(@event.Name);
                cxt.Writer.Write(" += value");
            }
            else
            {
                EmitUnsafeAddMethodAccessorForEvent(@event, @event.ContainingType, cxt);
                EmitUnsafeAddMethodInvocationForEvent(
                    @event,
                    cxt,
                    GeneratedInterfaceDataPropertyName);
            }

            cxt.Writer.Write(";");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionEnd();
        }

        if (@event.RemoveMethod is not null)
        {
            EmitAttributes(@event.RemoveMethod, withinType, cxt, false);
            cxt.Writer.Write("remove");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionStart();

            if (@event.IsPublicOrInternal())
            {
                cxt.Writer.Write(GeneratedInterfaceDataPropertyName);
                cxt.Writer.Write(".");
                cxt.Writer.Write(@event.Name);
                cxt.Writer.Write(" -= value");
            }
            else
            {
                EmitUnsafeRemoveMethodAccessorForEvent(@event, @event.ContainingType, cxt);
                EmitUnsafeRemoveMethodInvocationForEvent(
                    @event,
                    cxt,
                    GeneratedInterfaceDataPropertyName);
            }

            cxt.Writer.Write(";");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionEnd();
        }

        cxt.Writer.WriteBracedSectionEnd();

        EmitEventInvokeMethod(@event, withinType, cxt, isProxy: true);
    }

    private static void EmitEventInvokeMethod(
        IEventSymbol @event,
        INamedTypeSymbol withinType,
        TypeEmissionContext cxt,
        bool isProxy)
    {
        if (@event.Type is INamedTypeSymbol { DelegateInvokeMethod: not null } eventType)
        {
            if (isProxy)
            {
                cxt.Writer.Write("private");
            }
            else
            {
                cxt.Writer.Write("public");
            }
            cxt.Writer.Write(" ");
            if (@event.IsStatic)
            {
                cxt.Writer.Write("static ");
            }
            cxt.Writer.Write(eventType.DelegateInvokeMethod.ReturnType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
            cxt.Writer.Write(" ");
            cxt.Writer.Write(@event.Name);
            cxt.Writer.Write("_Invoke");
            EmitMethodParameterList(
                eventType.DelegateInvokeMethod,
                withinType,
                cxt);
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionStart();

            if (!eventType.DelegateInvokeMethod.ReturnsVoid)
            {
                cxt.Writer.Write("return ");
            }
            if (isProxy)
            {
                cxt.Writer.Write(GeneratedInterfaceDataPropertyName);
                cxt.Writer.Write(".");
                cxt.Writer.Write(@event.Name);
                cxt.Writer.Write("_");
            }
            else
            {
                cxt.Writer.Write(@event.Name);
                cxt.Writer.Write("?.");
            }
            cxt.Writer.Write("Invoke(");
            EmitUnparenthesizedArgumentListFromParameters(
                eventType.DelegateInvokeMethod.Parameters,
                cxt);
            cxt.Writer.Write(");");
            cxt.Writer.WriteLine();

            cxt.Writer.WriteBracedSectionEnd();
        }
    }

    private static void EmitUnsafeAccessorClassName(
        ISymbol symbol,
        INamedTypeSymbol currentType,
        TypeEmissionContext cxt)
    {
        if (currentType.ContainingType is null)
        {
            cxt.Writer.Write(symbol.ContainingType.OriginalDefinition.ToMangledFullyQualifiedWithoutGlobalNamespaceDisplayString());
            cxt.Writer.Write("_");
            cxt.Writer.Write(symbol.Name);
            if (symbol is IMethodSymbol method && !method.MethodKind.IsAccessor())
            {
                cxt.Writer.Write("_Arity");
                cxt.Writer.Write(method.TypeParameters.Length);
                cxt.Writer.Write("_StartParameters__");
                foreach ((var parameter, var last) in method.Parameters.WithLastFlag())
                {
                    cxt.Writer.Write(parameter.Type.ToMangledFullyQualifiedWithoutGlobalNamespaceDisplayString());
                    if (!last)
                    {
                        cxt.Writer.Write("_");
                    }
                }
                cxt.Writer.Write("__EndParameters");
            }
            cxt.Writer.Write("_");
            cxt.Writer.Write(currentType.OriginalDefinition.Name);
            cxt.Writer.Write("_Class");
        }
        else
        {
            cxt.Writer.Write(currentType.OriginalDefinition.Name);
        }
    }

    private static void EmitUnsafeAccessorClassQualification(
        ISymbol symbol,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt)
    {
        foreach (var type in declaringType.SelfAndContainingTypes().Reverse())
        {
            EmitUnsafeAccessorClassName(symbol, type, cxt);
            if (type.TypeArguments.Length > 0)
            {
                cxt.Writer.Write("<");
                foreach ((var typeArgument, var last) in type.TypeArguments.WithLastFlag())
                {
                    cxt.Writer.Write(typeArgument.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
                    if (!last)
                    {
                        cxt.Writer.Write(", ");
                    }
                }
                cxt.Writer.Write(">");
            }
            cxt.Writer.Write(".");
        }
    }

    private static void EmitUnsafeAccessorClassTopBun(
        ISymbol symbol,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt)
    {
        for (var i = 0; i < cxt.TypeStack.Count; i++)
        {
            CloseType(cxt);
        }

        foreach (var type in declaringType.SelfAndContainingTypes().Reverse())
        {
            if (type.ContainingType is null)
            {
                cxt.Writer.Write("file");
            }
            else
            {
                cxt.Writer.Write("public");
            }
            cxt.Writer.Write(" static class ");
            EmitUnsafeAccessorClassName(symbol, type, cxt);
            if (type.TypeParameters.Length > 0)
            {
                cxt.Writer.Write("<");
                foreach ((var typeParameter, var last) in type.TypeParameters.WithLastFlag())
                {
                    cxt.Writer.Write(typeParameter.Name);
                    if (!last)
                    {
                        cxt.Writer.Write(", ");
                    }
                }
                cxt.Writer.Write(">");
            }
            EmitConstraintClausesWithLeadingNewLineIfAny(type.TypeParameters, cxt);
            cxt.Writer.WriteLine();
            cxt.Writer.WriteBracedSectionStart();
        }
    }

    private static void EmitUnsafeAccessorClassBottomBun(
        ISymbol symbol,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt)
    {
        foreach (var type in declaringType.SelfAndContainingTypes().Reverse())
        {
            cxt.Writer.WriteBracedSectionEnd();
        }

        foreach (var type in cxt.TypeStack.Reverse())
        {
            OpenType(type, cxt);
        }
    }

    private static void EmitUnsafeGetterAccessorClassForProperty(
        IPropertySymbol property,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt)
    {
        EmitUnsafeAccessorClassTopBun(property.GetMethod!, declaringType, cxt);
        EmitUnsafeGetterAccessorForProperty(
            property.OriginalDefinition,
            declaringType.OriginalDefinition,
            cxt,
            includePublicModifier: true);
        EmitUnsafeAccessorClassBottomBun(property.GetMethod!, declaringType, cxt);
    }

    private static void EmitUnsafeGetterAccessorForProperty(
        IPropertySymbol property,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt,
        bool includePublicModifier = false)
    {
        cxt.Writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind.");
        if (property.IsStatic)
        {
            cxt.Writer.Write("Static");
        }
        cxt.Writer.Write("Method, Name=\"");
        cxt.Writer.Write(property.GetMethod!.Name);
        cxt.Writer.Write("\")]");
        cxt.Writer.WriteLine();
        if (includePublicModifier)
        {
            cxt.Writer.Write("public ");
        }
        cxt.Writer.Write("extern static ");
        cxt.Writer.Write(property.Type.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" ");
        cxt.Writer.Write(property.GetMethod!.Name);
        cxt.Writer.Write("(");
        cxt.Writer.Write(declaringType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" c");
        if (property.IsIndexer)
        {
            cxt.Writer.Write(", ");
            EmitUnparenthesizedParameterList(
                property.Parameters,
                null!,
                cxt,
                isForUnsafeAccessor: true);
        }
        cxt.Writer.Write(");");
        cxt.Writer.WriteLine();
    }

    private static void EmitUnsafeSetterAccessorClassForProperty(
        IPropertySymbol property,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt)
    {
        EmitUnsafeAccessorClassTopBun(property.SetMethod!, declaringType, cxt);
        EmitUnsafeSetterAccessorForProperty(
            property.OriginalDefinition,
            declaringType.OriginalDefinition,
            cxt,
            includePublicModifier: true);
        EmitUnsafeAccessorClassBottomBun(property.SetMethod!, declaringType, cxt);
    }

    private static void EmitUnsafeSetterAccessorForProperty(
        IPropertySymbol property,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt,
        bool includePublicModifier = false)
    {
        cxt.Writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind.");
        if (property.IsStatic)
        {
            cxt.Writer.Write("Static");
        }
        cxt.Writer.Write("Method, Name=\"");
        cxt.Writer.Write(property.SetMethod!.Name);
        cxt.Writer.Write("\")]");
        cxt.Writer.WriteLine();
        if (includePublicModifier)
        {
            cxt.Writer.Write("public ");
        }
        cxt.Writer.Write("extern static void ");
        cxt.Writer.Write(property.SetMethod!.Name);
        cxt.Writer.Write("(");
        cxt.Writer.Write(declaringType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" c");
        if (property.IsIndexer)
        {
            cxt.Writer.Write(", ");
            EmitUnparenthesizedParameterList(
                property.Parameters,
                null!,
                cxt,
                isForUnsafeAccessor: true);
        }
        cxt.Writer.Write(", ");
        cxt.Writer.Write(property.Type.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" ");
        cxt.Writer.Write("v);");
        cxt.Writer.WriteLine();
    }

    private static void EmitUnsafeGetterInvocationForProperty(
        IPropertySymbol property,
        TypeEmissionContext cxt,
        string targetString)
    {
        cxt.Writer.Write(property.GetMethod!.Name);
        cxt.Writer.Write("(");
        if (property.IsStatic)
        {
            cxt.Writer.Write("null!");
        }
        else
        {
            cxt.Writer.Write(targetString);
        }

        if (property.IsIndexer)
        {
            cxt.Writer.Write(", ");
            EmitUnparenthesizedArgumentListFromParameters(
                property.Parameters,
                cxt);
        }

        cxt.Writer.Write(")");
    }

    private static void EmitUnsafeSetterInvocationForProperty(
        IPropertySymbol property,
        TypeEmissionContext cxt,
        string targetString)
    {
        cxt.Writer.Write(property.SetMethod!.Name);
        cxt.Writer.Write("(");
        if (property.IsStatic)
        {
            cxt.Writer.Write("null!");
        }
        else
        {
            cxt.Writer.Write(targetString);
        }

        if (property.IsIndexer)
        {
            cxt.Writer.Write(", ");
            EmitUnparenthesizedArgumentListFromParameters(
                property.Parameters,
                cxt);
        }

        cxt.Writer.Write(", value)");
    }

    private static void EmitUnsafeAddMethodAccessorClassForEvent(
        IEventSymbol @event,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt)
    {
        EmitUnsafeAccessorClassTopBun(@event.AddMethod!, declaringType, cxt);
        EmitUnsafeAddMethodAccessorForEvent(
            @event.OriginalDefinition,
            declaringType.OriginalDefinition,
            cxt,
            includePublicModifier: true);
        EmitUnsafeAccessorClassBottomBun(@event.AddMethod!, declaringType, cxt);
    }

    private static void EmitUnsafeAddMethodAccessorForEvent(
        IEventSymbol @event,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt,
        bool includePublicModifier = false)
    {
        cxt.Writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind.");
        if (@event.IsStatic)
        {
            cxt.Writer.Write("Static");
        }
        cxt.Writer.Write("Method, Name=\"");
        cxt.Writer.Write(@event.AddMethod!.Name);
        cxt.Writer.Write("\")]");
        cxt.Writer.WriteLine();
        if (includePublicModifier)
        {
            cxt.Writer.Write("public ");
        }
        cxt.Writer.Write("extern static void ");
        cxt.Writer.Write(@event.AddMethod!.Name);
        cxt.Writer.Write("(");
        cxt.Writer.Write(declaringType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" c, ");
        cxt.Writer.Write(@event.Type.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" h);");
        cxt.Writer.WriteLine();
    }

    private static void EmitUnsafeRemoveMethodAccessorClassForEvent(
        IEventSymbol @event,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt)
    {
        EmitUnsafeAccessorClassTopBun(@event.RemoveMethod!, declaringType, cxt);
        EmitUnsafeRemoveMethodAccessorForEvent(
            @event.OriginalDefinition,
            declaringType.OriginalDefinition,
            cxt,
            includePublicModifier: true);
        EmitUnsafeAccessorClassBottomBun(@event.RemoveMethod!, declaringType, cxt);
    }

    private static void EmitUnsafeRemoveMethodAccessorForEvent(
        IEventSymbol @event,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt,
        bool includePublicModifier = false)
    {
        cxt.Writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind.");
        if (@event.IsStatic)
        {
            cxt.Writer.Write("Static");
        }
        cxt.Writer.Write("Method, Name=\"");
        cxt.Writer.Write(@event.RemoveMethod!.Name);
        cxt.Writer.Write("\")]");
        cxt.Writer.WriteLine();
        if (includePublicModifier)
        {
            cxt.Writer.Write("public ");
        }
        cxt.Writer.Write("extern static void ");
        cxt.Writer.Write(@event.RemoveMethod!.Name);
        cxt.Writer.Write("(");
        cxt.Writer.Write(declaringType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" c, ");
        cxt.Writer.Write(@event.Type.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" h);");
        cxt.Writer.WriteLine();
    }

    private static void EmitUnsafeAddMethodInvocationForEvent(
        IEventSymbol @event,
        TypeEmissionContext cxt,
        string targetString)
    {
        cxt.Writer.Write(@event.AddMethod!.Name);
        cxt.Writer.Write("(");
        if (@event.IsStatic)
        {
            cxt.Writer.Write("null!");
        }
        else
        {
            cxt.Writer.Write(targetString);
        }

        cxt.Writer.Write(", value)");
    }

    private static void EmitUnsafeRemoveMethodInvocationForEvent(
        IEventSymbol @event,
        TypeEmissionContext cxt,
        string targetString)
    {
        cxt.Writer.Write(@event.RemoveMethod!.Name);
        cxt.Writer.Write("(");
        if (@event.IsStatic)
        {
            cxt.Writer.Write("null!");
        }
        else
        {
            cxt.Writer.Write(targetString);
        }

        cxt.Writer.Write(", value)");
    }

    private static void EmitUnsafeAccessorClassForField(
        IFieldSymbol field,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt)
    {
        EmitUnsafeAccessorClassTopBun(field, declaringType, cxt);
        EmitUnsafeAccessorForField(
            field.OriginalDefinition,
            declaringType.OriginalDefinition,
            cxt,
            includePublicModifier: true);
        EmitUnsafeAccessorClassBottomBun(field, declaringType, cxt);
    }

    private static void EmitUnsafeAccessorForField(
        IFieldSymbol field,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt,
        bool includePublicModifier = false)
    {
        cxt.Writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind.");
        if (field.IsStatic)
        {
            cxt.Writer.Write("Static");
        }
        cxt.Writer.Write("Field, Name=\"");
        cxt.Writer.Write(field.Name);
        cxt.Writer.Write("\")]");
        cxt.Writer.WriteLine();
        if (includePublicModifier)
        {
            cxt.Writer.Write("public");
        }
        else
        {
            cxt.Writer.Write("private");
        }
        cxt.Writer.Write(" extern static ref ");
        cxt.Writer.Write(field.Type.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" ");
        field.WriteUnsafeAccessorName(cxt.Writer);
        cxt.Writer.Write("(");
        cxt.Writer.Write(declaringType.ToFullyQualifiedWithNullableReferenceTypeAnnotationsDisplayString());
        cxt.Writer.Write(" c);");
        cxt.Writer.WriteLine();
    }

    private static void EmitUnsafeAccessorClassForMethod(
        IMethodSymbol method,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt)
    {
        EmitUnsafeAccessorClassTopBun(method, declaringType, cxt);
        EmitUnsafeAccessorForMethod(
            method.OriginalDefinition,
            declaringType.OriginalDefinition,
            cxt,
            includePublicModifier: true);
        EmitUnsafeAccessorClassBottomBun(method, declaringType, cxt);
    }

    private static void EmitUnsafeAccessorForMethod(
        IMethodSymbol method,
        INamedTypeSymbol declaringType,
        TypeEmissionContext cxt,
        bool includePublicModifier = false)
    {
        cxt.Writer.Write("[global::System.Runtime.CompilerServices.UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind.");
        if (method.IsStatic)
        {
            cxt.Writer.Write("Static");
        }
        cxt.Writer.Write("Method, Name=\"");
        cxt.Writer.Write(method.Name);
        cxt.Writer.Write("\")]");
        cxt.Writer.WriteLine();
        if (includePublicModifier)
        {
            cxt.Writer.Write("public ");
        }
        cxt.Writer.Write("extern static ");
        EmitMethodCoreSignature(
            method,
            declaringType,
            null!,
            cxt,
            isForUnsafeAccessor: true);
        cxt.Writer.Write(";");
        cxt.Writer.WriteLine();
    }

    public class EmitTypesArgs
    {
        public int StartIndex;
        public int StopIndex;

        public EmitTypesArgs(int startIndex, int stopIndex)
        {
            StartIndex = startIndex;
            StopIndex = stopIndex;
        }
    }
}
